### ISSUE TITLE
Architectural question: Why is the vm async?

### ISSUE THREAD

**Issue by aakilfernandes** [ethereumjs/ethereumjs-vm#116]
Having some issues that I think are related to the saynchronous nature of the vm, so I was wondering what the reasoning was. It might shed some light on my issue. Thanks!

**Comment by wanderer** [comment]
well I guess ultimate reason why is that the merkle-trie was built on leveldown and that has an async api. Pretty much all info (state & blocks) are stored in leveldown. And Many opcode access those things at runtime.

**Comment by kumavis** [comment]
also allows light clients to perform lazy state lookups
