### ISSUE TITLE
runCode swallows errors

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-vm#117]
runCode does not distinguish between legit errors (stack underflow) and catastrophic errors (state read failure).

I had a bug in my overridden `vm.stateManager._lookupStorageTrie` method that threw an error.

This error was swallowed and the vm continued as if nothing was wrong until the `stateRoot` did not match

**Comment by holgerd77** [comment]
I will close this now just to avoid confusion so that we have one place to discuss this.
