### ISSUE TITLE
in `runCall.js` `subTxValue()` is called every time 

### ISSUE THREAD

**Issue by conroydamien** [ethereumjs/ethereumjs-vm#121]
Hi - I noticed while calling an external library function from a `payable` function i.e. resulting in a `DELEGATECALL` rather than a `JUMP`, that `subTxValue()` (in `runCall.js`) was called each time and the caller had `value` deducted from their account for each such call... I figure that there should be some way of telling from the `opts` when `subTxValue()` should be called and when it shouldn't, I just haven't figured it out... Thanks!

**Comment by axic** [comment]
Fixed by #84.
