### ISSUE TITLE
[Dev Env Improvement] Add pre-commit hook

### ISSUE THREAD

**Issue by sdtsui** [ethereumjs/ethereumjs-vm#141]
Based on suggestion from @jwasinger :  
- Add a pre-commit hook so it is harder to push, setting clearer expectations for new contributors, and improving the overall quality of code.
- Note: This can be skipped by contributors with write access, through `git push --no-verify...`.

**Comment by julianduque** [comment]
@sdtsui this should include a `CONTRIBUTING.md` file in the repository 

An example from the Node.js project:

https://github.com/nodejs/node/blob/master/CONTRIBUTING.md

Also, a `COLLABORATOR_GUIDE.md` is very useful to onboard new contributors to the project and to define de proper git workflow.

Example:
https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md

**Comment by axic** [comment]
I think the pre-commit hook is not needed anymore since we've set better permissions on pushing/merging. A contributors guide would be a great addition though!
