### ISSUE TITLE
CREATE opcode is broken

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#178]
The opcode doesn't transmit the code: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L519

Effectively it always creates an empty account.

The tests seem not to be very useful, for example: https://github.com/ethereum/tests/blob/45f8be4196b2830728d4b1ea1b7564ad89e6ab0c/GeneralStateTests/stCreateTest/CREATE_EmptyContractWithBalance.json

Which is `GAS PUSH1 0x0 SSTORE PUSH1 0x20 PUSH1 0x0 PUSH1 0x1 CREATE PUSH1 0x1 SSTORE GAS PUSH1 0x64 SSTORE`, but I don't see any expected storage values in the test JSON.

**Comment by cdetrio** [comment]
The code is loaded [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L861)  (called from [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L527-L534).  Perhaps this could be refactored for clarity, and `checkCallMemCost` renamed to something like `checkCallMemCostAndLoadData`

**Comment by axic** [comment]
Yeah figured out since, cleaning it up breaks some tests, see #179.

**Comment by winsvega** [comment]
that specific test check that the code will create an empty contract with non empty balance

**Comment by axic** [comment]
@winsvega yes, but couldn't find any which actually compares the expected storage values

**Comment by winsvega** [comment]
expected storage values in which test?
