### ISSUE TITLE
Simulated RPC backend

### ISSUE THREAD

**Issue by lukehedger** [ethereumjs/ethereumjs-vm#182]
General question: is there anything like the [Geth simulated backend](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts#blockchain-simulator) in the JS world? Specifically, in terms of unit testing without the need for a live RPC backend.

Any pointers to existing tools/ideas would be great as well. Thanks!

**Comment by axic** [comment]
You might want to check out https://github.com/ethereumjs/testrpc which uses this VM and provides an RPC interface.

**Comment by lukehedger** [comment]
Thanks for responding @axic. Not particularly helpful though! The idea here is to **remove** the need to run something like TestRPC when executing unit tests. Proper unit tests should not rely on open network connections. No worries if you do not have any thoughts on this though.
