### ISSUE TITLE
rustbn.js cwrap introduces eval

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-vm#227]
The use of an eval statement affects security policy warnings in browsers, and requires a more lax security configuration.

it seems like cwrap is using the eval to build a new function from dynamically created js source and return it. If this is the case, **this doesn't need to be done at runtime**, and can be part of a build step for a module between `rustbn.js` and `ethereumjs-vm`

```js
var bn128Module = require('rustbn.js');
bn128Module.cwrap('ec_add', 'string', ['string'])
```

**Comment by kumavis** [comment]
here is the generated js:
```js
(function($0) {var stack = Runtime.stackSave();var str = $0;var ret=0;if(str!==null&&str!==undefined&&str!==0){var len=(str.length<<2)+1;ret=Runtime.stackAlloc(len);stringToUTF8(str,ret,len)};$0=(ret);var ret = cfunc($0);ret = Pointer_stringify(ret);Runtime.stackRestore(stack);return ret})
```
it has some external references ( `Runtime`, `stringToUTF8`, `cfunc`, `Pointer_stringify` ), making breaking out this slightly more difficult.

I'm still confident this function can be built at compile time and distributed as a module.

**Comment by kumavis** [comment]
@jwasinger @axic @wanderer  do you know of a way to build these methods ahead of time?

**Comment by axic** [comment]
Emscripten needs to be passed this flag to disable the use of `eval`: `-s NO_DYNAMIC_EXECUTION=1`

cc @cdetrio @holgerd77

**Comment by hugo-dc** [comment]
Submitted PR https://github.com/ethereumjs/rustbn.js/pull/7 on rustbn.js to set flag NO_DYNAMIC_EXECUTION to 1.

**Comment by axic** [comment]
With #215 the dependency had been updated to require the fix. This should be closed now.

@jwasinger @holgerd77 a release of the VM should be made I guess?
