### ISSUE TITLE
`delegatecall` incorrectly handling exceptions

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#228]
Cross-reference of https://github.com/ethereumjs/testrpc/issues/355

Needs to be investigated if issue is still present in post-Byzantium vm.

(are there no tests to cover this?)

**Comment by lastperson** [comment]
Not reproducible in remix, and not reproducible in testrpc 6.0.3. Probably can be closed.

**Comment by holgerd77** [comment]
Ok, thanks, will close now.
