### ISSUE TITLE
Collision tests are failing (consensus bug)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#232]
#### Description

The testing team recently added collision tests, testing the (unlikely but possible case) that a ``CREATE`` call is trying to create a contract on an existing address (hence: (address) collision).

These tests are still failing in the vm, failing tests cases:

- ``CreateCollisionToEmpty`` ([test](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stCreateTest/CreateCollisionToEmpty.json) | [filler](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stCreateTest/CreateCollisionToEmptyFiller.json))
- ``TransactionCollisionToEmptyButCode``
- ``TransactionCollisionToEmptyButNonce``

#### Work Status

What I've got so far:

There has to be some additional check for account existence in ``runCall.js`` in the ``loadToAccount`` function in the form of:

```
stateManager.exists(toAddress, function (err, exists) {
  if (exists) {
    // This is new, stop/revert the execution
  } else {         
    stateManager.getAccount(createdAddress, function (err, account) {
      // Go on with the normal stuff...
    })
  }
})
```

I'm just not sure, what the semantics are here. Should the ``CREATE`` call just return and do nothing? Or throwing an OOG error? Some (detailed) hint on that would be helpful.

#### Reproduce

The following command produces a stack trace for a failing ``CreateCollisionToEmpty`` test:

```
node tests/tester -s --customStateTest='./CreateCollisionToEmpty.json' --data=2 --gas=0 --value=0 --jsontrace
```

[Here](https://gist.github.com/holgerd77/5f2b4d77e8e33a1ed8df8a702c6f4c53) is a gist with the succeeding stack trace from pyethereum.

**Comment by pirapira** [comment]
`CREATE` should overwrite the existing code.

That overwriting behavior will change once https://github.com/ethereum/EIPs/pull/208/files#diff-95b306e6e6d2d6dbb0c5fd3ac4ea45c4R27 is activated, but this EIP was postponed to Constantinople or later.

**Comment by holgerd77** [comment]
@pirapira Ah, thanks so much!

**Comment by holgerd77** [comment]
@pirapira ah, maybe as an addition: what are the differences then? Are there any differences in gas costs compared to a normal ``CREATE`` execution (I'm getting different gas costs then in the pyethereum stack)? Other?

**Comment by pirapira** [comment]
There should be no differences in gas consumption (overwriting = newly deploying).

I'm just trying up to conjure up the relevant YP page in my head though.

**Comment by pirapira** [comment]
And the existing nonce (as well as the code) should be just forgotten.

**Comment by axic** [comment]
@holgerd77 I think these tests are passing now?

**Comment by axic** [comment]
I didn't know they were commented out, but since we pass the "almost latest" tests repo I assumed they would be working.

**Comment by holgerd77** [comment]
Fixed (on the sideline 😄) by https://github.com/ethereumjs/ethereumjs-vm/pull/329, will close.
