### ISSUE TITLE
DELEGATECALL should receive only 63/64 of the remaining gas (and msg.gas should reflect that)

### ISSUE THREAD

**Issue by benjamincburns** [ethereumjs/ethereumjs-vm#255]
Passing this one along. See trufflesuite/ganache-cli#367 for more detail.

I suspect the fix is simple, just change [this line](https://github.com/ethereumjs/ethereumjs-vm/blob/f1a8db69fefd484246442d5873321df0e9118512/lib/opFns.js#L698) to something like `gasLimit: gas.sub(runState.gasLeft.sub(runState.gasLeft.div(64))`

I haven't read the yellow paper too carefully on this subject - it's possible that similar gas reductions should apply for other `*CALL` opcodes.

**Comment by axic** [comment]
It applies to all of them, including create.

**Comment by axic** [comment]
But please `checkOutOfGas` does that: https://github.com/ethereumjs/ethereumjs-vm/blob/f1a8db69fefd484246442d5873321df0e9118512/lib/opFns.js#L1005-L1010

**Comment by carver** [comment]
I think the GAS opcode should reflect the reduced gas.

**Comment by axic** [comment]
@benjamincburns @holgerd77 Apparently ethereumjs-vm passes all the state tests. Is this really a bug in ethereumjs-vm or the consumer of ethereumjs-vm?

**Comment by holgerd77** [comment]
I've scanned through the ``ganache-core`` release notes linked by @davidmurdoch in [this comment](https://github.com/trufflesuite/ganache-cli/issues/367#issuecomment-477694270). As far as I understand them I would assume this a) has been solved and b) is not an issue where there is still some underlying problem within the VM.

Will close this for now, feel free to reopen if my understanding of this was not correct.
