### ISSUE TITLE
fails to clear mapping storage slots

### ISSUE THREAD

**Issue by benjamincburns** [ethereumjs/ethereumjs-vm#257]
Another one from our archives which is likely misattributed to Ganache: trufflesuite/ganache-cli#294

**Comment by axic** [comment]
It would be very benficial creating actual test cases for these and submitting them to https://github.com/ethereum/tests.

ethereumjs-vm passes those tests and if there are actually bugs, they should be part of the official test suite. This applies to the other issue too.

**Comment by benjamincburns** [comment]
Agreed, though I'm somewhat time limited at the moment. I'll do my best to circle back around to this in the next couple weeks if nobody else picks it up in the interim.

**Comment by axic** [comment]
cc @winsvega

**Comment by benjamincburns** [comment]
"The other one" was #255

**Comment by winsvega** [comment]
Looks like a solidity issue

**Comment by hugo-dc** [comment]
I checked this problem and here is what I've found so far: When you clear storage you get gas refund, so, when ganache executes eth_estimateGas the estimated gas considers the gas refund and at the end the total gas is less than the base fee, this is why when executing the real transaction with a low gas limit ethereumjs-vm is throwing that error.

Should ganache check that the estimated gas is not lower than the base fee?

**Comment by axic** [comment]
Gas refunds should not be taken int consideration by `estimateGas` as they are only returned after the transaction has finished.

**Comment by cdetrio** [comment]
this would be a good test case for the `eth_estimateGas` rpc method https://github.com/ethereum/EIPs/issues/217.

**Comment by holgerd77** [comment]
Referenced Ganache issue is now closed, seemed to be VM unrelated. Will close, feel free to reopen if necessary.
