### ISSUE TITLE
Easier way/description to run custom Solidity contract through VM

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#277]
Currently it is relatively "hacky"/intransparent how to get from custom Solidity code to an executable example in the VM, e.g. to test https://github.com/trufflesuite/ganache-cli/issues/367.

It would be good to have this supported at least through better documentation in the ``README`` or through some test template or similar.

Will have a deeper look into this later, you can also post your strategies here.

**Comment by holgerd77** [comment]
Related: #128

**Comment by alcuadrado** [comment]
Isn't this covered by this example https://github.com/ethereumjs/ethereumjs-vm/tree/master/examples/run-solidity-contract? It's a little complicated, but I don't think it can be simplified much further.

**Comment by holgerd77** [comment]
Oh, sorry, had a bit forgotten about that. Will close.
