### ISSUE TITLE
Race condition on step when doing async operations in event handler (e.g. reading storage)

### ISSUE THREAD

**Issue by benjamincburns** [ethereumjs/ethereumjs-vm#278]
The step hook is implemented [here](https://github.com/ethereumjs/ethereumjs-vm/blob/ad1333a1c5a1067c9eaa4dc1371d662a6c94dda8/lib/runCode.js#L133-L153).

If in my event handler I wish to carry out some asynchronous state inspection (e.g. call `vm.stateManager.getContractStorage(...)`), it appears that there's nothing which prevents the VM from continuing on with its processing while this asynchronous operation is occurring. This makes it difficult to reliably inspect the state of contract storage during program execution.

**Comment by benjamincburns** [comment]
An obvious workaround to this for inspecting `SLOAD` operations is to inspect the stack on the next `step` event just after an `SLOAD`. However, for an `SSTORE`, it's impossible to get the storage value that's being changed.

**Comment by benjamincburns** [comment]
It seems that the VM already is an instance of `AsyncEventEmitter` - this gives me some hope for an easy fix - just need to make the VM wait for the `emit` callback before proceeding. I'll take a crack at that and submit a PR if I can get it working.

**Comment by benjamincburns** [comment]
Wow, I'm dumb sometimes... handling the `emit` callback is already being done!

/me reenrolls in the David Zoolander School for Kids who can't Read Good

:blush:

**Comment by holgerd77** [comment]
@benjamincburns That needs pretty-much some time to get familiar with such a code base, no need to dumbify oneself! 😄 😺
