### ISSUE TITLE
SSTORE fee equals 0

### ISSUE THREAD

**Issue by yann300** [ethereumjs/ethereumjs-vm#290]
In the `step` event

**Comment by yann300** [comment]
in `data.opcode.fee`

**Comment by holgerd77** [comment]
Yes, this is just returning the static base costs from [opcodes.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opcodes.js), which is ``0`` for ``SSTORE``.

Will close this, if this behavior is causing problems for someone please comment here.
