### ISSUE TITLE
VMTests should pass

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-vm#294]
Right now a lot are failing and `npm run testVM` fails with an exception.

**Comment by cdetrio** [comment]
This might make sense after the VM test cleanup in https://github.com/ethereum/tests/issues/449 (and elsewhere) is finished. Currently the VM tests require a custom VM that doesn't execute CALLs. (the lack of such a custom VM is one reason why ethereumjs-vm fails some of the VM tests). The cleanup is going to remove all the VM tests that do CALLs, then the VM tests can be run on a standard VM. However, even after the cleanup the VM tests will still be using Frontier gas costs. So ethereumjs-vm would need a feature to switch to Frontier gas costs (lack of this feature is the second reason ethereumjs-vm fails some of the VM tests).

My preference would be to generate the VM tests in the state test format, and add those to [ethereum/tests](https://github.com/ethereum/tests). Then we can just run the state tests without worrying whether we're missing any VM coverage. The purpose of the VM tests is mainly for new EVM prototypes (where they have ADD and SUB working but haven't yet implemented CALLs and state roots), anyway.

**Comment by jwasinger** [comment]
> My preference would be to generate the VM tests in the state test format, and add those to ethereum/tests. Then we can just run the state tests without worrying whether we're missing any VM coverage. The purpose of the VM tests is mainly for new EVM prototypes (where they have ADD and SUB working but haven't yet implemented CALLs and state roots), anyway.

Agreed.

**Comment by holgerd77** [comment]
This seems to be very much in the open and not really predicable when pre-conditions are tackled. Will close for now.
