### ISSUE TITLE
StateManager Should be public

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/ethereumjs-vm#33]
It would be nice to expose the StateManager publically. And split it into its own module. What should the API be?

**Comment by wanderer** [comment]
currently the API is
* getAccount
* exists // checks if an account exists
* _putAccount
* getAccountBalance
* putAccountBalance
* putContractCode
* getContractCode
* _lookupStorageTrie
* _getStorageTrie
* getContractStorage
* putContractStorage
* commitContracts
* revertContracts
* getBlockHash
* checkpoint
* commit
* revert
* getStateRoot
* warmCache
* dumpStorage
* hasGenesisState
* generateCanonicalGenesis
* generateGenesis

Also It would be nice to inculde the following from https://github.com/ethereumjs/ethereumjs-account

* account.getCode(trie, cb)
* account.setCode(trie, code, cb)
* account.getStorage(trie, key, cb)
* account.setStorage(trie, key, val, cb)

**Comment by kumavis** [comment]
for the provider engine I wanted to be able to override contract code set/gets and storage set/gets
https://github.com/MetaMask/provider-engine/blob/master/subproviders/vm.js#L74-L80

**Comment by kumavis** [comment]
Here is an example of how providing a custom StateManager could be very useful
https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/hooked.js

**Comment by kumavis** [comment]
here is an example of a module consumer overwriting StateManager https://github.com/ethereum/browser-solidity/pull/345/files
