### ISSUE TITLE
Obtaining Internal Transactions - Replaying Blocks/Transactions

### ISSUE THREAD

**Issue by istrau2** [ethereumjs/ethereumjs-vm#343]
I am using infura for a node. I would like to pull internal transactions for a block and/or transaction. I've written code as the docs direct but am getting strange errors. Here is the code:

```
const Web3 = require("web3");
const VM = require('ethereumjs-vm');
const Tx = require('ethereumjs-tx');
const blockFromRpc = require('ethereumjs-block/from-rpc');
const web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/' + process.env.INFURA_API_KEY));

const vm = new VM();

web3.eth.getBlock(6189875)
    .then(block => {
        try {
            vm.runBlock({
                block: blockFromRpc(block),
                //block
            }, function(err, results){
                console.log('returned: ' + results.logs);
            });
        }
        catch(e) {
            const i = e;
        }
    });
```

which errors in:
> base free exceeds gas limit

I feel like perhaps I am not instantiating the `vm` correctly....

I've posted a [stackexchange question](https://ethereum.stackexchange.com/questions/57233/how-to-use-ethereumjs-vm-to-find-the-internal-transactions-for-a-transaction-blo) as well

**Comment by holgerd77** [comment]
Too old for a useful answer, will close.
