### ISSUE TITLE
error: Failed to decode output: Error: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by lailys** [ethereumjs/ethereumjs-vm#344]
keep getting this error on this code

**Comment by lailys** [comment]
I meant anyone knows the solution?

**Comment by holgerd77** [comment]
You have to provide a more thorough issue description with some information on your environment and a code example to reproduce your error, otherwise it is not possible to help you.

**Comment by holgerd77** [comment]
No context provided, will close.
