### ISSUE TITLE
Some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by lailys** [ethereumjs/ethereumjs-vm#349]
│ High          │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ hbsify [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ hbsify > handlebars                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/61  

this is a vulnerability I get and I am not sure how to update the handlebars version

**Comment by holgerd77** [comment]
Handlebars isn't a dependecy within the virtual machine, this has to be added somewhere else in your project, will close.
