### ISSUE TITLE
Using runTx with disabled cache

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#353]
`runTx` accepts the option `populateCache` which I thought would disable cache when executing the transaction. However, currently this is [failing](#352) due to `runTx` using `stateManager.cache` methods such as `get` and `put` in 8 occasions to look up and update accounts in the trie.

One suggestion is to use `stateManager` methods instead of directly using `stateManager.cache`, and move the `populateCache` option to `stateManager`, which would use cache or not underneath depending on the value of `populateCache`.

It seems this might be the direction that was intended, as `stateManager` does have methods `getAccount` and `putAccount` which call the cache methods. However, they don't support the flag to disable cache. Is this maybe work in progress?

**Comment by holgerd77** [comment]
Related to the work in https://github.com/ethereumjs/ethereumjs-vm/issues/268.

**Comment by holgerd77** [comment]
Is this still an issue? //cc @ryanio

**Comment by ryanio** [comment]
hm we don't have the populateCache option anymore in runTx. i believe we have a more sophisticated cache in the statemanger now, probably by design as @s1na kept working on it.

@s1na would you consider this issue resolved?

**Comment by s1na** [comment]
wow this issue is from even before I joined the team so I'm a bit hazy on the details :) If the `populateCache` option is not present anymore we can close this.

**Comment by holgerd77** [comment]
@s1na we proudly have issues still open within the repo dating back to 2016 https://github.com/ethereumjs/ethereumjs-vm/issues/114, maybe if this ages a bit more we can sell this high if it ages a bit more (like wine or so). 😜 😂
