### ISSUE TITLE
[Constantinople] EIP 1014 CREATE2 Opcode

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#356]
EIP: [EIP 1014](https://github.com/ethereum/EIPs/pull/1014) 
Work in progress: PR [#329](https://github.com/ethereumjs/ethereumjs-vm/pull/329)

Test Situation:
Many tests implemented
[Tests](https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stCreate2) | [Filler](https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stCreate2)

**Comment by rmeissner** [comment]
@holgerd77 just out of curiosity do you plan a release of the intermediate state (e.g. 2.4.1) or only a release once everything is done. 

I would love to create a PR on ganache-core to enable constantinople testing (via a flag) and would love to have create2 in there :D

**Comment by holgerd77** [comment]
@rmeissner Hmm, I have a strong tendency to wait until things are completed and then do a bigger release, sorry, please give this another 2-3 weeks.

The StateManager changes by @mattdean-digicatapult are coming to a close with I think one PR + the API documentation missing, also Constantinople is close to the finish line. Currently hanging is actually only the EXTCODEHASH implementation https://github.com/ethereumjs/ethereumjs-vm/pull/326, with the tests not yet all written on the ``ethereum/tests`` side, if you want to help out there as well that would be really appreciated.

Once these things come together I thinking of eventually do even a ``v3.0.0`` release, think this might very well be justified, the other thing where we are getting really close to passing all the state + blockchain tests, just a handful of state tests and 20 blockchain tests missing. If we get these down even further this would be a biggie together with the other changes from above.

**Comment by rmeissner** [comment]
I will take a look at #326 but this might have to wait a little :)

**Comment by snario** [comment]
Hey guys what's the update here? I'm still getting `contract not deployed` errors when using the `create2 `opcode on a chain that's using this library (ganache-cli).

**Comment by rstormsf** [comment]
@rmeissner @holgerd77 `create2` opcode doesn't seem to be working with ganache

```js
assembly {
      proxy := create2(0, add(initcode, 0x20), mload(initcode), 0)
    }
```

**Comment by rmeissner** [comment]
@rstormsf would be nice to see an example, since we have some test with create2 and ganache running for the Gnosis Safe (see https://github.com/gnosis/safe-contracts/blob/development/contracts/proxies/ProxyFactory.sol#L50, https://github.com/gnosis/safe-contracts/blob/development/test/gnosisSafePersonalEditionCreation2.js#L47 and https://travis-ci.org/gnosis/safe-contracts/builds/506170858#L750)

**Comment by snario** [comment]
I'll try to re-use this new `ProxyFactory` contract and see how that plays out.

**Comment by rstormsf** [comment]
@rmeissner False positive.
I'm sorry I just re-tried it and it seems to be working fine

https://www.youtube.com/watch?v=LcDIX-ZQksU&feature=youtu.be

@snario take a look. it's working with ganache-cli
