### ISSUE TITLE
EIP 1186: RPC call `eth_getProof`

### ISSUE THREAD

**Issue by zmitton** [ethereumjs/ethereumjs-vm#389]
[https://github.com/ethereum/EIPs/issues/1186](https://github.com/ethereum/EIPs/issues/1186)

**Comment by holgerd77** [comment]
What's the context?

**Comment by zmitton** [comment]
I just want to see it added to the js. Im not sure if this is the right repo for the change though.

**Comment by rmeissner** [comment]
I would say this is more something for https://github.com/trufflesuite/ganache-core or any other library that provides rpc endpoints. This repo is for the execution engine (virtual machine) of ethereum and does not provide rpc endpoints implementations
