### ISSUE TITLE
New release 2.5: Constantinople, StateManager, Consensus

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#391]
//cc @mattdean-digicatapult, @axic, @rmeissner 

Since we are making good progress on both Constantinople ``EXTCODEHASH`` and the StateManager changes, I would now target a ``v2.5.0`` release for the VM next Wednesday, November  21st, will open this issue here if there is some need for discussion around this.

---

### EXTCODEHASH

@rmeissner: let me know if you have reservations regarding the ``EXTCODEHASH`` implementation, but this should be more-or-less ready, or am I wrong?

---

### StateManager

@mattdean-digicatapult (and everyone reading):
Regarding the ``StateManager`` I would take the following approach: for at least this release and probably 2-3 more I would keep the ``StateManager`` within the VM, I think we should expose the API and move the status from ``experimental`` to ``beta``. If people are already integrating with/do manipulations on the current/previous state manager, I would encourage them very much in the release notes to update to the changed-here API and follow-up on further changes. In the coming 2-3 releases of the VM I would do separate ``StateMangager`` changes release notes and at some point we should shift to a ``release candidate`` version.

My idea for documentation of the API for this release would be, that we keep this separate, maybe simply do a doc build by manual command, e.g.

```shell
documentation build ./lib/stateManger.js --format md --shallow > ./docs/stateManager.md
```

(not tested, just for inspiration), and link from a separate paragraph within the API section of the README doing some explanations along. Does this make sense?

After these stabelizing releases, I do think we should target to extract the ``StateManager`` from the VM, with the main benefit that this will largely help internally to keep a stable API on this and from a user perspective helps to switch state managers and also increases confidence in the stability of the API. There are also some other benefits like code size on exchange and reusability for other purposes.

On top note: this might also trigger more dedicated work on the state manager itself, like people working on different cache backends or the like.

A ``StateManager`` extracting release should then be labelled ``v3.0.0``.

---

So far to the ``StateManger``, everyone having suggestions or questions on the release or the notes above please comment!

**Comment by holgerd77** [comment]
Ah, and @mattdean-digicatapult, do you think you can do an API doc PR (eventually with some API tweaks discussed) until Monday or latest Tuesday morning?

**Comment by rmeissner** [comment]
@holgerd77 from my side `EXTCODEHASH` is ready. The last failing constantinople test should not be related to this. If I have time later today, I will check why it is failing and submit a fix if possible.

**Comment by axic** [comment]
I will try to get #172 fixed today, but don't want to block the release on it. Hopefully it makes it into master by Monday.

**Comment by mattdean-digicatapult** [comment]
@holgerd77, I don't think I'll get the API docs finished today (other work commitments) but I should be able to get this in on Monday.

**Comment by holgerd77** [comment]
@axic Cool!

@mattdean-digicatapult: ok, thanks!

**Comment by holgerd77** [comment]
Would do a release tomorrow on this if there is no objection or need for further discussion or changes.

**Comment by holgerd77** [comment]
Closed by https://github.com/ethereumjs/ethereumjs-vm/pull/394.
