### ISSUE TITLE
Hello, my company is developing a ether wallet, ether node has been set up, with the Geth. But now there is a problem, that is, how to query the wallet address under the transaction records. Do you need to parse the node's leveldb file, can you give me some ideas? Thank you.

### ISSUE THREAD

**Issue by liuhuanhui** [ethereumjs/ethereumjs-vm#396]
Hello, my company is developing a ether wallet, ether node has been set up, with the Geth. But now there is a problem, that is, how to query the wallet address under the transaction records. Do you need to parse the node's leveldb file, can you give me some ideas? Thank you.

**Comment by holgerd77** [comment]
This is not a place for generic questions, will close. You might want to look at the [web3.js](https://github.com/ethereum/web3.js/) library respectively read on your problem in the associated [docs](https://web3js.readthedocs.io/en/1.0/), this should be closer to your problem.

Please don't repeat opening repeated issues with overblown headlines there, this is generally regarded as bad behavior, but ask on the Forum or Gitter channel respectively do some reading in the documentation first. Thanks!
