### ISSUE TITLE
Incomplete gas calculation for LOG opcodes

### ISSUE THREAD

**Issue by pinkiebell** [ethereumjs/ethereumjs-vm#404]
Right now, all LOG operations are consuming 375 of gas.
We should adhere to spec. from the yellow paper:
```
Glog 375 Partial payment for a LOG operation.
Glogdata 8 Paid for each byte in a LOG operation’s data.
Glogtopic 375 Paid for each topic of a LOG operation.
```

**Comment by holgerd77** [comment]
Could you link to the parts in the code where this is calculated + where the gas price is defined for reference?

**Comment by pinkiebell** [comment]
Base cost is defined here: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opcodes.js#L144

I think that needs custom handling for example in:
https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCode.js#L190

**Comment by holgerd77** [comment]
Also was this gas calculation mechanism like this from the beginning or did it change along one of the hardforks?

**Comment by axic** [comment]
The custom handling is here: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L505

**Comment by pinkiebell** [comment]
@holgerd77 
Oh, I don't know. I was looking at the `BYZANTIUM VERSION 12779ac - 2018-11-2725` version.

@axic I'm taking a dive. Maybe it doesn't work because I push stack elements in the 'step' event? 😅

**Comment by pinkiebell** [comment]
Hmm, sorry for the noise. The gas calculation seems fine.
However
```
  gas: <BN: fffffffffb77>,
  return: <Buffer >,
  gasUsed: <BN: 488> }
```
gasUsed seems to be wrong (thats for LOG2)
should be 1160

**Comment by axic** [comment]
I think that is misleading again, because likely it displays it as base-16. 0x488 (hex) = 1160 (decimal)

**Comment by pinkiebell** [comment]
@axic 😅 Thanks! Late night error from my side. 

I think the issue can be closed 👍
