### ISSUE TITLE
`opts.state` and `opts.activatePrecompiles` are not compatible

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-vm#411]
https://github.com/ethereumjs/ethereumjs-vm/pull/376 made a change that makes the following happen:

```
var myTrie = new Trie();
var vm = new VM({
   state: myTrie,
   activatePrecompiles: true
});
myTrie.root.equals(myTrie.EMPTY_TRIE_ROOT); // true
myTrie.root.equals(vm.statemanager._trie.root); // false
```

`opts.state` is no longer used by the internal StateManager. Is this intentional?

**Comment by holgerd77** [comment]
Just checked, this is actually only happening with the combination of also setting `activatePrecompiles: true` you're applying above. In the code there is then the trie newly instantiated (see [code](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/index.js#L60)).

I would very much assume that this is a bug and should be fixed, any other opinions why this mgith be there and if it could have a reasoning?

@davidmurdoch how urgent is this for you?

**Comment by davidmurdoch** [comment]
I think it was just missed in the nit of refactoring done in #376, seems like a bug to me.

For ganache-core we can temporarily work around it by creating the precompile entries in our own state trie, and set `activatePrecompiles` to `false` when creating the VM instance. 

We can just do something like this:

```JavaScript
const createStateTrie = function(db, root) {
  const trie = new Trie(db, root);
  for (var i = 1; i <= 8; i++) {
    trie.put(new BN(i).toArrayLike(Buffer, "be", 20), new Account().serialize());
  }
  return trie;
};
const vm = new VM({state: createStateTrie(data.trie_db, block.header.stateRoot)});
```

We currently don't have any tests for precompiled contracts in ganache-core, so I'm not 100% confident we actually _need_ it.

So to answer your question directly: it's not very urgent for us.

**Comment by holgerd77** [comment]
Thanks for the detailed answer, will try to do a big fix release on this anyhow ASAP. This is a serious bug and shouldn't be left in the code for too long.

Not sure if I'll make it before Christmas though.
