### ISSUE TITLE
Request for a public API to flush the cache to the trie

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-vm#418]
Ganache-core previously used the public `cache` object in the VM's `stateManager` to flush the cache to the trie -- as we use `putAccount` (which only writes to the cache, not the trie) to initialize accounts with a starting balance when creating the VM.

Now that `cache` is private, is there another API for syncing the cache and the trie, and if not, could one be added? Alternatively, we could come up with another way of initializing the accounts (we could potentially write the accounts to our own trie that we pass to the vm on initialization).

**Comment by s1na** [comment]
Not sure if its stable yet, but the `checkpoint` + `commit` API might be useful for modifying the state trie directly (`commit` calls `flush` internally). @holgerd77 would such a use-case be aligned with the intention behind `commit`?

**Comment by holgerd77** [comment]
Will circle in @mattdean-digicatapult since he will be the better person to answer this.

**Comment by mattdean-digicatapult** [comment]
There are a few options here, but firstly I should say that the cache methods were removed from `stateManager` intentionally so as to hide internal details from the interface. Therefore adding them back would not be a great option unless there was an extremely compelling reason.

My first idea is to do as @s1na says; construct the `stateManager`, call `checkpoint` make your changes and then `commit`. That would add the accounts and wouldn't involve any direct state trie manipulations.

Another idea might be to just add the accounts to the state trie prior to constructing `stateManager`. This clearly only works well at startup, but is how our unit tests initialize accounts I believe.

Another longer term option would be to actually construct your own `stateManager` implementation that exposes the features you require. It's not a very complicated interface but I get that this might be more work than you want to do for the Constantinople support ticket referenced.

Lastly, most simple but most ugly, is that you could just interact with the cache directly under `stateManager._cache`. The API hasn't really changed and it should work. If Constantinople support is the absolute priority this is probably the quickest way of getting there, but I would strongly recommend one of the other options be implemented shortly after as a separate ticket.

**Comment by davidmurdoch** [comment]
Thanks @mattdean-digicatapult. We'll ship this week with direct `_cache` access and move to one of the other options in the next release.
