### ISSUE TITLE
Deprecate createHookedVm

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#435]
As per the jsdoc, `createHookedVm` is "a helper for creating a vm with modified state lookups, this should be made obsolete by a better public API for StateManager". Given the recent changes in `StateManager`, I'm wondering if the use-cases that prompted this helper are already covered by the new API, and if not, what should be added to allow deprecating `createHookedVm`?

**Comment by holgerd77** [comment]
I did searched on GitHub ``ethereumjs``, ``ethereum`` (e.g. for remix) and ``trufflesuite`` organizations and as well as a google search for ``createHookedVm`` and found no references whatsoever. Not sure if we are running some phantom debate here. 😄 Eventually we can really just drop?

**Comment by s1na** [comment]
:laughing: Will create a PR

**Comment by holgerd77** [comment]
Addressed in #451, will close.

**Comment by axic** [comment]
It is used in Metamask's provider-engine: https://github.com/MetaMask/provider-engine/blob/master/subproviders/vm.js

Which was used to run gas estimation and calls on the client. Not sure if Metamask still does that or delegates it to Infura.

**Comment by axic** [comment]
What his means is ethereumjs-vm should have a version bump to 3.x.

**Comment by holgerd77** [comment]
//cc @danfinley @whymarrh

**Comment by holgerd77** [comment]
//cc @danfinlay

**Comment by holgerd77** [comment]
@axic Yes, I was thinking about doing some minor version bump release integrating the latest refactoring work, which is all not really breaking but might nevertheless cause the one or the other challenges depending on how deep people integrate with the VM code.

**Comment by axic** [comment]
Well removing the hooked vm I would say is a major bump since it removes functionality in a breaking way.

**Comment by holgerd77** [comment]
Ah sorry, I thought you were referring to the ``x`` in ``3.x``, didn't have a close-enough look, yes, probably a major version bump is justified (necessary).

Think we'll generally wait a bit with the release so that there is some more time for discussion, also @s1na can eventually some more of the integrations of #424 he is planning.
