### ISSUE TITLE
`stateManager.setStateRoot` doesn't clear the `_storageTries` cache.

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-vm#444]
https://github.com/ethereumjs/ethereumjs-vm/issues/417 was about the `_cache` which was fixed in https://github.com/ethereumjs/ethereumjs-vm/pull/420. This issue is about `_storageTries` https://github.com/ethereumjs/ethereumjs-vm/blob/c842d101108d6acdd9ca82ab1de274ba3b16e5b2/lib/state/stateManager.js#L38

which I think should also get cleared when the stateRoot is set.

We ran into the issue with Ganache when a user creates a snapshot (which just means we record the block number at the time `snapshot` was called), then modifies contract storage, reverts the snapshot (we just set the state root back to the way it was when the snapshot was created), then _modifies_ contract storage again.

PR and tests to follow.

**Comment by s1na** [comment]
What you're describing seems to be really similar to what `commit` and `revert` in `stateManager` are supposed to do. Have you checked them out by any chance? `revert` does clear both the state cache and the contract storage cache.

**Comment by davidmurdoch** [comment]
Because we can't `checkpoint()` before calling `runBlock` (since: https://github.com/ethereumjs/ethereumjs-vm/commit/eddd9db5a1430631d3482d0c17b21e4b44fc6f60#diff-bbc749b6f8c7177c7960ea582daf8f63R371) there are many situations where `commit`/`revert` will no longer work (as of v2.5.0).

Clearing the storage cache when it becomes invalid seems like an appropriate fix to me, as the accounts cache is currently cleared when it becomes invalid: https://github.com/ethereumjs/ethereumjs-vm/commit/09b8bfba689b2cdac4adce45dd867623979911b2.

**Comment by holgerd77** [comment]
//cc @mattdean-digicatapult

**Comment by mattdean-digicatapult** [comment]
This looks like a bug exactly as described by @davidmurdoch. The simplest solution is as described; just clear the storage caches in `setStateRoot` whenever we clear `_cache`.
