### ISSUE TITLE
tx.from

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-vm#46]
tx.from has been removed
its still used all over the vm
e.g. https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runTx.js

**Comment by kumavis** [comment]
this isnt a problem bc we're currently pointing at
```
"ethereumjs-tx": "git://github.com/ethereumjs/ethereumjs-tx.git#fromproperty",
```

**Comment by wanderer** [comment]
@kumavis do you think you can fix this?

**Comment by kumavis** [comment]
was re-added to ethereumjs-tx
