### ISSUE TITLE
Locking dependencies

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#467]
It was previously discussed in https://github.com/ethereumjs/ethereumjs-vm/pull/451 to lock dependencies to specific versions (rather flexible semver) to prevent an error in a package in the dependency graph to break builds and hinder development (see #451 for example).

At Ethcc, @iurimatias mentioned they started doing this (either in remix or embark, can't remember) for security reasons, after the npm package vulnerability incident, and suggested using [shrinkwrap](https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/) to help with managing dependencies of dependencies.

I like to open up this discussion again, because I think it'd help if we were more in control of the dependencies and it's worth the additional effort of every once in a while updating the packages manually or with greenkeeper.

**Comment by rumkin** [comment]
I think it's not a question that need a discussion. It's already a standard in secure and reliable code development.

**Comment by alcuadrado** [comment]
I've expressed many times in our other communication channels that this would be a mistake. I've found [this article](https://www.twilio.com/blog/lockfiles-nodejs) that summarizes most of my thoughts about this, so I'm sharing it here.

What's missing in this article is that using shrinkwrap is an incomplete solution, as it is not supported by yarn. It doesn't mention why shrikwrap shouldn't be used in libraries either. IMO the main reason is that it quickly leads to dependencies being duplicated, making the library unusable for the web.

**Comment by evertonfraga** [comment]
We have instrumentation in place to detect when tests fail with direct dependencies ([example](https://github.com/ethereumjs/ethereumjs-blockchain/issues/129)) and with indirect (deeper) dependencies (https://github.com/ethereumjs/ethereumjs-vm/issues/610). Soon we'll have scheduled jobs for all major `ethereumjs` packages.

That said, I am interested to know of any other mechanisms to keep them safe.

**Comment by rumkin** [comment]
@alcuadrado While the web related issue is good for working out, the yarn statement isn't relevant as I think. Yarn uses NPM registry, but has its own lockfile which is not compatible with NPM's. Thus Yarn fragmentizes infrastructure with incompatible solution, what seems bad to me. And it should be solved somehow by yarn.

The only issue I see here is one provided by Snyk.io [problem with malicious package-lock.json in Pull Request](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/). This one could be solved with package source checker util, which will verify package name and url in lockfile to belong to NPM registry.

**Comment by holgerd77** [comment]
Will close this for now since the majority consensus seems to stay on the "no package-lock.json" file side of things, feel free to re-open if you feel there are significant new view points to be added to this discussion.
