### ISSUE TITLE
Issue [Unverified] VM Throwing with Basic Method and Contract

### ISSUE THREAD

**Issue by SilentCicero** [ethereumjs/ethereumjs-vm#475]
So I don't have the time to do a full one-over on this, but I was using Ethereum JS VM with a very basic contract, with a single method and no code within the method (sol version 5+). My code remains the same, when i upgraded from VM version 2.5.1 to version 2.6.0, the method when called failed. I reverted back to VM version 2.5.1 and now it all works.

I know this error / issue is not fully filed but I would look into this. 

To recreate: use a basic contract with a single method, and deploying the contract / calling the method (no method code, no input vars in the method, no constructor). And doing a comparison between 2.5.1 and 2.6.0. 2.6.0 fails, while 2.5.1 does not.

This blew up my testing harness, for no reason other than just the ethjs-vm version. I reverted, all is fine now.

**Comment by s1na** [comment]
Thanks for reporting!

Do you have by any chance an error stack? or could you maybe share a link to the failing test case in your harness (if the source is public)?

**Comment by holgerd77** [comment]
@SilentCicero Do you have an update on this respectively did you go back to use the latest VM version and the respective test(s) worked again as expected?

**Comment by holgerd77** [comment]
No follow-up and referencing a two-old VM version (2.6), will close for now.
