### ISSUE TITLE
Incorrect SSTORE gas fees / deprecated EIP-1283 implementation active by default results in SSTORE gas cost of 0

### ISSUE THREAD

**Issue by DominicBruetschChainsecurity** [ethereumjs/ethereumjs-vm#484]
Brief Summary :
*  EIP-1283 SSTORE gas fees implementation still present and default in `ethereumjs-vm` but this EIP has been removed from CONSTANTINOPLE with the PETERSBURG update and is not live on mainnet
* `Ethereumjs-common` was already updated to PETERSBURG and removed the gas prices related to the EIP-1283 / set them 0. This results in all calculations by `ethereumjs-vm` on the SSTORE gas costs which would have been entitled to reduced gas costs as specified by EIP-1283  to return 0 currently.

Consequently gas costs for the SSTORE operation in `ethereumjs-vm` are not correct.

---

The current ethreumjs-vm code implements EIP-1283 and uses it per default to compute gas costs for SSTORE operations. EIP-1283 was removed from the Constantinople hardfork however as a  vulnerability was found. Thus it's not part of the current Ethereum EVM specifications, but `Ethereumjs-vm` still implements it per default and as a result, computes the gas cost for this operation incorrectly. Chainspec is set to `PETERSBURG` and the updated gas prices in  `Ethereumjs-common` return 0 for the gas prices defined by EIP-1283 as it has been removed. Thus all SSTORE gas costs calculations which would have been entitled to a discount under EIP-1283 return 0.

Suggest to revert these changes in order to become compliant again with the default Ethereum VM implementation for the current `PETERSBURG` version:
https://github.com/ethereumjs/ethereumjs-vm/commit/397d510baaefe5277fc0b6697ca4d873e17600f1#diff-25e3f46da81521d0b8d46602585f0ac3

Example:
The current EIP-1283 implementation of `ethereum-js` of the SSTORE operation returns a gas cost of 0 e.g. when storing the same value as already present in the storage slot. This is due to `ethereumjs-common` already having removed the gas cost parameters for EIP-1283:

```
      // If current value equals new value (this is a no-op), 200 gas is deducted.
      subGas(runState, new BN(runState._common.param('gasPrices', 'netSstoreNoopGas')))
```

If you check the current `ethereumjs-common` implementation for Petersburg, all these parameters (e.g. `netSstoreNoopGas` in the example above) have been set to none/0.

**Comment by s1na** [comment]
@holgerd77 I'll try and see if I can reproduce this today. If so, should we wait in #482 to include the fix for this issue in v3.0 as well?

**Comment by s1na** [comment]
@DominicBruetschChainsecurity Thanks for creating the issue. I still haven't been able to fully understand the problem.

`ethereumjs-vm` **does** implement EIP-1283, and calculates the gas costs accordingly but only when the hardfork is set to `constantinople`:

https://github.com/ethereumjs/ethereumjs-vm/blob/f0e310b0fc9639f41d5aafc46eb0c97303578b94/lib/evm/opFns.js#L1220-L1221

However, if hardfork is not `constantinople` (either HFs before or after, which includes `petersburg`):

https://github.com/ethereumjs/ethereumjs-vm/blob/f0e310b0fc9639f41d5aafc46eb0c97303578b94/lib/evm/opFns.js#L1265-L1270

Please note that even though `ethereumjs-common` sets the EIP-1283 gas price parameters to `null` (e.g. `netSstoreNoopGas`), for the non-EIP-1283, it uses the old gas price parameters, namely `sstoreReset`, `sstoreSet`, `sstoreRefund`. As such from my understanding the behaviour is correct.

> The current EIP-1283 implementation of ethereum-js of the SSTORE operation returns a gas cost of 0 e.g. when storing the same value as already present in the storage slot

Do you maybe have an example code snippet or test case you can share that shows this?

**Comment by holgerd77** [comment]
Will close here, feel free to re-open if there is still need for discussion.
