### ISSUE TITLE
Istanbul EIP 1803: Rename opcodes for clarity

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#519]
Part of #501, implementation of [EIP 1803](https://eips.ethereum.org/EIPS/eip-1803).

Thought a bit about this. While generally relatively trivial we should nevertheless give this some additional thought and come up with some generalized structure how to cleanly handle cases like this.

In the past we already had this ``SUICIDE`` -> ``SELFDESTRUCT`` renaming, this was simply renamed here https://github.com/ethereumjs/ethereumjs-vm/pull/153.

We should now come up with a somewhat more general structure where both the old and new names remain transparent and choice is cleanly done along a HF switch without adding too much boilerplate to the code.

I first thought about adding this to the [ethereumjs-common](https://github.com/ethereumjs/ethereumjs-common) library, but this might be overblown after thinking this over again, so it's likely best to directly add it here to the VM.

I would suggest that someone taking on with this first makes a short suggestion on how best to integrate here.

**Comment by s1na** [comment]
> We should now come up with a somewhat more general structure where both the old and new names remain transparent and choice is cleanly done along a HF switch without adding too much boilerplate to the code.

That would make it clear that the name changed at some point, and could be done if it helps with readability. Just wanted to add that it's not strictly necessary, as renaming opcodes does not require a hardfork (since the important thing is their byte representation).

**Comment by holgerd77** [comment]
This will likely not make it into Istanbul due to the lack of reference implementations and tests, so I will close this for now.
