### ISSUE TITLE
Should homestead be configurable?

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#52]
Right now homestead (e.g. support for `DELEGATECALL`) is turned on based the block number. Would it make sense having that as an option in runCode/runTx?

Would make supporting delegatecall in `browser-solidity` easy: https://github.com/chriseth/browser-solidity/pull/119

**Comment by kumavis** [comment]
yeah, I approve of this feature. does the morden testnet use a different block number for homestead?

**Comment by axic** [comment]
Perhaps it is, I'm not sure.

The current VM would work as a node on the live net properly (if there would be a full JS node..), but the use cases it faces (provider-engine, testrpc, browser-solidity) won't have an appropriate block number so it is losing out.

**Comment by chriseth** [comment]
yes, morden uses 494000 as transition point

**Comment by chriseth** [comment]
Oh and just to clarify: This is not about "making delegatecall easy in browser-solidity", it is about making libraries work again in browser-solidity, they fail 100% without this configuration option. :-)

**Comment by wanderer** [comment]
would it work for everyone if we just defaulted to after homestead?

**Comment by kumavis** [comment]
@wanderer yeah i think that works

**Comment by chriseth** [comment]
Any progress on this?

**Comment by wanderer** [comment]
@chriseth merged in #55 and published as ethereumjs-vm@1.3.0

**Comment by wanderer** [comment]
also updated docs

**Comment by axic** [comment]
Does this also enables it for runTx?

**Comment by wanderer** [comment]
@axic right now its a gobal options https://github.com/ethereumjs/ethereumjs-vm/pull/55/files#diff-6d186b954a58d5bb740f73d84fe39073R33 but we could add it each run level

**Comment by chriseth** [comment]
Wohoo! Thanks a lot!
