### ISSUE TITLE
Drop VMTests

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#520]
As discussed in #513, the [VMTests](https://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html) suite only supports `Homestead`. This library however supports from `Byzantium` upwards. The `VMTestsRunner` is not needed any more and can be dropped to avoid confusions (it can be re-introduced if the test suite is updated).

**Comment by jochem-brouwer** [comment]
Closed by #788 ? (@ryanio)

**Comment by ryanio** [comment]
yes, thanks @jochem-brouwer!
