### ISSUE TITLE
Uniform use of VmError for exceptions

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#521]
Two minor points about how the VM handles exceptions:

- In most parts of the evm, exceptions are wrapped in a `VmError`. There are places however where this is not the case (e.g. in precompiles) and only the error message is returned as a string. This can be made uniform so that all exceptions are wrapped in a `VmError`.
- Result objects include two keys: `exception` and `exceptionError`. This is redundant. It can be checked whether an exception occured by checking whether `exceptionError` is null or contains a value.

**Comment by holgerd77** [comment]
Not sure what's the state of this, this would need some validation - optimally with some code links - or some comment by @s1na if/what of the above has been solved.

**Comment by alcuadrado** [comment]
I think this was fixed in https://github.com/ethereumjs/ethereumjs-vm/pull/551
