### ISSUE TITLE
Contract creation should follow the YP and keep balance

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#53]
According to the YP during contract creation the balance should be taken from the previous state (if it existed) plus the endowment.

Currently ethereumjs-vm won't keep the balance.

go-ethereum implements it properly: https://github.com/ethereum/go-ethereum/blob/c541b38fb36587d23c60f5e2f2b9b3c8700ec489/core/state/statedb.go#L283

**Comment by wanderer** [comment]
we do the same thing.
Here we get the old account https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCall.js#L69
and here we write the newly created code https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCall.js#L174
