### ISSUE TITLE
Default blocks are created without Common objects

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#530]
I'm not sure if this affects the actual execution, but whenever a `Block` is created as default value to a parameter, it's done without passing it the VM's `Common`.

That happens in these places:

1. https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runTx.ts#L68
2. https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runCall.ts#L37
3. https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runCode.ts#L75

I can create a PR for this, but I'm not sure how to test it.

**Comment by holgerd77** [comment]
Regardless if currently affecting execution or not, this should definitely be integrated.

Testing: not sure, maybe it's possible to use the [DIFFICULTY](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/evm/opFns.ts#L453) opcode for that and add to the [api/runBlock.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/api/runBlock.js) or - eventually - [api/runCode.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/api/runCode.js) tests (or at least take some inspiration from there).


Side note: have updated the code links above to point again to the correct lines after some "shifting by aging". 😄

**Comment by holgerd77** [comment]
(addition on the tests: so should be able to get these tests to fail before the changes applied by instantiating the VM with MuirGlacier, the blank / non-Common `Block` initializations should the create `petersburg` blocks with a non-fitting difficulty I would assume)

**Comment by holgerd77** [comment]
Have re-checked, 1. is fixed on the Block v3 update, 2., 3. still open. Should be easily fixable, in doubt we should leave the tests alternatively to have this issue open for another 1 1/2 years. 😁

**Comment by ryanio** [comment]
haha, i can definitely add to my short-term TODO list. should i add some tests too or just fix the cases?
