### ISSUE TITLE
StateManager#getContractStorage's buffer sizes

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#557]
Yesterday I lost 1-2 debugging hours until I realized that `StateManager#getContractStorage`:

1. It expects its `key` parameter to be padded to `32` bytes, and doesn't fail if it has a different size. It just returns something unrelated, most probably, an empty `Buffer`.

2. It can return `Buffer`s of size lower than `32` bytes.

I think these things should, at least, be documented. Or maybe, for (1), it could throw or pad the `Buffer` if needed. For (2), it could pad it. 

I'm more inclined to just throw in (1) and document (2).

**Comment by holgerd77** [comment]
Would also throw for (1) (especially since we have a breaking release on the door) and document (2).

**Comment by s1na** [comment]
Sounds good.

**Comment by alcuadrado** [comment]
So that's why it doesn't always return 32bytes `Buffer`s, right? Documenting it should be enough. I can prepare a PR later today.
