### ISSUE TITLE
It's unclear how to revert a `runBlock` call

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#558]
I'm copying some messages I sent to @s1na through gitter to open the conversation, as this may bring more ideas on how to improve this situation.

---

I have this function that takes a tx, and runs it in a new block:

```ts
async runTransactionInNewBlock(tx: Transaction): Promise<RunBlockResult> {
    await this._validateTransaction(tx);
    await this._saveTransactionAsReceived(tx);

    const block = await this._getNextBlockTemplate();
    const needsTimestampIncrease = await this._timestampClashesWithPreviousBlockOne(
      block
    );

    if (needsTimestampIncrease) {
      await this._increaseBlockTimestamp(block);
    }

    await this._addTransactionToBlock(block, tx);

    const previousRoot = await this._stateManager.getStateRoot();

    let result: RunBlockResult;
    try {
      result = await this._vm.runBlock({ block, generate: true });

      await this._manageErrors(result.results[0].vm);

      if (needsTimestampIncrease) {
        await this.increaseTime(new BN(1));
      }

      await this._saveBlockAsSuccessfullyRun(block, result);
      await this._saveTransactionAsSuccessfullyRun(tx, block);

      return result;
    } catch (error) {
      // We set the state root to the previous one. This is equivalent to a
      // rollback of this block.
      await this._stateManager.setStateRoot(previousRoot);

      throw error;
    }
  }
``

If the tx fails, I want to revert everything and throw an error. My first idea was to use the state manager's checkpoint and commit functions but if I call `StateManger#checkpoint` before `VM#runBlock` I get this error `Cannot get state root with uncommitted checkpoints`.

It comes from this part of `runBlock`:
```ts
  // Persist state
  await state.commit()
  const stateRoot = await state.getStateRoot()
```

So my question is: is changing the state root to the previous one enough to mimic a state revert? I'd say it is, but I know nothing about the state cache.

---

Ideally, checkpointing before a `runBlock` shouldn't fail. I have no idea how much work this would take though. Documenting how to do this (maybe an example?) would work for now.

**Comment by s1na** [comment]
Ideally you shouldn't need to revert it manually. On failure, `runBlock` reverts the state itself. It shouldn't have any other side effect. Do you want to revert even on success?

Doing checkpoint before `runBlock` fails on `await state.getStateRoot()` as you mentioned. Getting the computed state root to verify against the block header is necessary, I don't see any way around it. So one option I see is to analyze whether we can allow `getStateRoot` even when there are pending checkpoints? I don't think it's possible with the current implementation. I'm just wondering whether it's conceptually possible

**Comment by alcuadrado** [comment]
I'm updating this just in case it's helpful for someone in the future.

What I wanted to do is revert a successfully processed block if its first transaction failed, and throw an error in that case. `runBlock` does revert the state, but when the block processing fails. That's not my case.

The solution I proposed above works because `setStateRoot` clears the `StateManager`'s caches.

Thank you @s1na for your help here and on gitter. I'm closing this issue now.
