### ISSUE TITLE
Investigate gpu.js

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#56]
Investigate how https://github.com/gpujs/gpu.js could speed up ethereumjs-vm. Good find @wanderer

**Comment by wanderer** [comment]
the find need to be contributed to @jeffscottward :)

**Comment by kumavis** [comment]
AFAIK using the GPU we get SIMD, but we don't run many computations in parallel. One exception might be if we had a state tree with a lazy stateRoot generation, and then it could re-hash all the new leaves in parallel.

**Comment by wanderer** [comment]
i think wasm supersedes this
