### ISSUE TITLE
Unnecessary dynamic field in OpcodeInfo

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#573]
The `dynamic` field in `OpcodeInfo` doesn't seem to be used in the code. It's probably there for historical reasons. Haven't yet found what purpose it served but I guess we can remove it.

**Comment by holgerd77** [comment]
@s1na If I am not completely wrong I think you removed the usage on this yourself during your refactoring work? 😄 😋 Yes, I think this can be removed now.
