### ISSUE TITLE
Events before and after executing a Message

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#574]
I'm currently working in Solidity debugging tools using the VM, and I'm having a hard time getting the complete picture of what a tx does. This is because running a tx sometimes implies running multiple messages.

I need to construct something like this, but I think it's not possible right now:

```ts
interface MessageTrace {
  code: Buffer | number; // The bytecode or precompile number that the message executed
  value: BN;
  calldata: Buffer;
  returnData: Buffer;
  error?: VmError;
  steps: MessageTraceStep[];
}

type MessageTraceStep = MessageTrace | EvmStep;

interface EvmStep {
  pc: number;
  /* ... Anything obtainable from the VM's step event, I'm OK here */
}
```

Adding events on `beforeMessage` and `afterMessage` should be enough.

What do you think @s1na @holgerd77 ? Am I missing something?

I can prepare a PR for this if you agree.

**Comment by alcuadrado** [comment]
I monkey-patched the EVM module like this

```ts
  const original = EVM.prototype.executeMessage;

  EVM.prototype.executeMessage = async function(
    message: Message
  ): Promise<EVMResult> {
    await this._vm._emit("beforeMessage", message);

    const result = await original.call(this, message);

    await this._vm._emit("afterMessage", result);

    return result;
  };
```

and was able to get all the data I needed. 

I think these events would be a great addition. It's not possible to observe the whole execution of a tx without them.

**Comment by holgerd77** [comment]
@s1na might want to add since he has implemented the `Message` logic, but I am not seeing why this shouldn't be added, sounds logically well positioned and pretty-much useful.

**Comment by s1na** [comment]
I agree, this makes sense to me and I don't see any reason why we shouldn't add this.
