### ISSUE TITLE
Remove support for node 0.11/0.12

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#58]
Because of the dependency of `ethereumjs-tx`, Travis fails on those two versions.  `-tx` has removed support for 0.11/0.12 so it makes sense to do the same here?

Note: *removing support* means removing it from Travis and adding a note into the README.

**Comment by wanderer** [comment]
sounds good to me

**Comment by axic** [comment]
This was removed from Travis.
