### ISSUE TITLE
Group precompiles based on HF

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#585]
While working on #584 I noticed that the precompiles are not dependent on the HF at all. This means a bytecode running in Byzantium could call the blake2f precompile which is being introduced in Istanbul!

The simplest fix would be to check in the precompile code if the HF is greater than the one in which the precompile was introduced. A better one would be to have a list of precompiles for each HF, and merge them similar to the approach discussed in #543.

**Comment by jochem-brouwer** [comment]
Heya! Since I'm introducing the BLS precompiles I really think this should be added first. See [the PR](https://github.com/ethereumjs/ethereumjs-vm/pull/783) =)
