### ISSUE TITLE
Genesis stateRoot incorrect for Goerli testnet due to account balances

### ISSUE THREAD

**Issue by whalelephant** [ethereumjs/ethereumjs-vm#586]
I have found that when using `vm.stateManager.generateCanonicalGenesis`, where the stateManager is specified for the Goerli testnet, the genesis block stateRoot generated is incorrect. 

The account balance from str -> Buffer in [stateManager](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/state/stateManager.ts#L529) needs some formatting:
```
 account.balance = new BN(initState[address].slice(2), 16).toArrayLike(Buffer)
```

The `initState` account balances from ethereumjs-common is prefixed with '0x' Goerli (not sure if this is a decision for other purposes as they are not for mainnet.

**Comment by s1na** [comment]
Thanks for tracking down the problem. As a temporary fix we could strip the `0x` prefix if one exists. I noticed that the genesis files are inconsistent on this. It's not only Goerli that has the `0x` prefix. Also found https://github.com/ethereumjs/ethereumjs-common/issues/30 and https://github.com/ethereum/EIPs/issues/1085. @holgerd77 it seems you were participating in the discussion back then, is there some consensus on the formatting of the genesis state?

**Comment by holgerd77** [comment]
Yes, at the time we fixed the address formatting but not yet the balances on the Common library. I think this is one of the many open issues on the libraries which is not unimportant but which we can't prioritize right now (this would need another major release on the Common side).

So I would also suggest to do the temporary fix @s1na suggested and strip the `0x` prefix. We should nevertheless also add tests here for the `vm.stateManager.generateCanonicalGenesis()` function to check against the genesis block state root for all major networks I would say.
