### ISSUE TITLE
Documentation about awaiting async events

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-vm#599]
It might be my lack of Javascript knowledge but it took me a while to figure this out. The idea is to use the `step` event of the VM and make execute some async calls which we want to await before we continue executing the next step in the VM. An use case for this is to run a "handmade" mainnet fork to test some code on: copy the chain code and once it tries to read storage for anything (e.g. balance/`SLOAD`/`EXTCODECOPY`) we first read this from the blockchain itself, dump it in our VM chain and then continue executing.

From the docs I assumed that I could create an `async` event where I await these web3 calls - but this does *NOT* yield the VM.

The solution is to:

```
      function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
      }

      chain.on('step', async function (data, nextEventFunction) {
        await sleep(1000)
        nextEventFunction()
      })
```

The `nextEventFunction` MUST get called if it is provided as an argument in the function (if the argument length > 1 this MUST get called). 

This also has the weird side effect that if, for some reason, you create a function (does not even have to be `async`) which you attach to an event which has more than 1 argument in it, the VM will stop immediately after firing the event if you do NOT call the second argument.

**Comment by alcuadrado** [comment]
Hey @jochem-brouwer, sorry for the confusion!

I was wrong about how this behaved, and I wrote that documentation. Most of my vm-related projects were running just by chance 🤦🏻‍♂️

I'll create a PR fixing the docs.

**Comment by jochem-brouwer** [comment]
To be honest I would have just assumed that if you would "normally" await things in the emitted event it would also yield the event - but apparently it does not =)
