### ISSUE TITLE
Enable cron job for tests

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#610]
It seems it's not quite feasible to run all tests for every commit at this moment. So we'd like to have the tests that are less likely to break to run daily.

- [x] nightly run without dependency cache
- [x] slow tests
- [x] all supported hard-forks to date

The ideal scenario is to have the tests running for every open PR, but as we currently have 18 branches, we need to make a choice:
- run on branches defined by name. currently it means only on `master`
- run for all branches, which would need some housekeeping on our stale branches.

On the other hand, we can look into other ways to optimize/parallelize tests.

Context: https://github.com/ethereumjs/ethereumjs-vm/pull/607#discussion_r343653267

**Comment by holgerd77** [comment]
I think we should start slowly here, if we run this against `master` this would be already some large improvement.

**Comment by ryanio** [comment]
This is now solved with the nightly test runner in #628 🙂

**Comment by evertonfraga** [comment]
Partly! we've got the slow tests on the VM and old hard fork tests, that's a good thing to run from time to time

**Comment by ryanio** [comment]
Sorry about closing this prematurely!

I started a PR to integrate a nightly slow state test here: https://github.com/ryanio/ethereumjs-vm/pull/7

I merged it into my fork to see what will happen tonight when it runs, to see how github actions reacts to the job taking ~30 mins. I will report back with a link to the results tomorrow.

According to [here in the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits),  "Each job in a workflow can run for up to 6 hours of execution time.", which is crazy but we'll see!

**Comment by ryanio** [comment]
It looks like it worked! It succeeded in 2h 17m, wow: https://github.com/ryanio/ethereumjs-vm/commit/12f7acc94e2ac5fcae91cf7a0668655d18eb0b50/checks?check_suite_id=361578920

**Comment by holgerd77** [comment]
Great! 😄 Hope this doesn't overstrain the infrastructure, hmm. 🙄 What does actually happen if a test fails, does anyone get an email or is something turning red or the like? So is this noticeable?

**Comment by evertonfraga** [comment]
On a test, I got email alerts when my vm fork had failing jobs. Hope that extends to ethereumjs as well.

**Comment by holgerd77** [comment]
@evertonfraga ah, cool! 👍

Side question + thread hijacking: do you have got some time to prepare this `block` release during the next 1-2 hours? I would otherwise prepare this now? Would you be available for short-term reviews on this (same timeframe)?

**Comment by evertonfraga** [comment]
To simplify things I pulled @ryanio PR to this repo and rebased from master. New PR at #639.

**Comment by ryanio** [comment]
Ok it looks like all the discussed tasks in this issue are merged :)
