### ISSUE TITLE
Remove extra condition for decimal genesis balances

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#615]
After https://github.com/ethereumjs/ethereumjs-common/pull/73 all genesis balances in the common library are in hex form, thanks to @evertonfraga. This means we shouldn't need this check anymore:

https://github.com/ethereumjs/ethereumjs-vm/blob/00d8fe3c7941fe571581fff1cd4e327980928127/lib/state/stateManager.ts#L529-L533

(See https://github.com/ethereumjs/ethereumjs-vm/pull/589 for why it was introduced)

**Comment by alcuadrado** [comment]
Makes sense. 

Should we also validate that the balances are `0x`-prefixed hex strings? This method is not called from any performance-critical path, so it wouldn't have any runtime impact, but would prevent bugs.

**Comment by s1na** [comment]
Yep validation sounds good!

**Comment by evertonfraga** [comment]
@alcuadrado good idea, will add it to the tests of ethereumjs-common.

**Comment by holgerd77** [comment]
@evertonfraga has this been addressed here?

**Comment by holgerd77** [comment]
Checked the code base, not an issue any more latest with the introduction of the new `Account` class, will close.
