### ISSUE TITLE
errors occuring in beforeBlock,afterBlock event handlers are treated as invalid blocks

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-vm#62]
https://github.com/ethereumjs/ethereumjs-vm/blob/19a83f71d913a0e7c96d851c0ed192a9fba5a479/lib/runBlock.js#L50-L56

no error is thrown -- these errors can be simple typos, makes it hard to debug

``` js
vm.on('afterBlock', function(block){
  // typo or other accidentally error
  throw new Error()
})
```

**Comment by axic** [comment]
What do you propose?

Note, this behaviour is shared with all the other events in the vm.

**Comment by holgerd77** [comment]
Open for > 2 years with no one picking it up, will close for now.
