### ISSUE TITLE
Labels for monorepo

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#629]
Given that the monorepo will contain issues and PRs specific to each module, I propose that we create labels to identify them. 

It can be used in conjunction with [Autolabeler](https://github.com/actions/labeler) to label PRs automatically.

Here's an example, using color `#FCCCC6`.

<img src="https://user-images.githubusercontent.com/47108/70555624-6e965880-1b4d-11ea-9a09-c78027787b9c.png" width=230>

**Comment by holgerd77** [comment]
Nice. 😄 I find the color choice fitting and not too interfering with other labels. But if someone has other suggestions, we can also change.
