### ISSUE TITLE
documentation: Webpack  : Module not found: Error: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by wighawag** [ethereumjs/ethereumjs-vm#638]
Hi, I want to use ethereumjs-vm in my web app and use webpack 

I get the following error:

```
ERROR in ./node_modules/rustbn.js/lib/index.asm.js
Module not found: Error: Can't resolve 'fs' in '/home/.../webapp/node_modules/rustbn.js/lib'
 @ ./node_modules/rustbn.js/lib/index.asm.js 1:1297-1310 1:153609-153622
 @ ./node_modules/rustbn.js/index.js
 @ ./node_modules/ethereumjs-vm/dist/evm/precompiles/06-ecadd.js
 @ ./node_modules/ethereumjs-vm/dist/evm/precompiles/index.js
 @ ./node_modules/ethereumjs-vm/dist/evm/evm.js
 @ ./node_modules/ethereumjs-vm/dist/runCall.js
 @ ./node_modules/ethereumjs-vm/dist/index.js
 ...
```

I fixed it with

```
  node: { 
    fs: 'empty'
  }
```
in webpack.config.js

**Comment by ryanio** [comment]
Have you seen [Running the VM in a browser](https://github.com/ethereumjs/ethereumjs-vm/tree/master/examples/run-code-browser)?

**Comment by wighawag** [comment]
yes, but this uses browserify, not webpack

**Comment by ryanio** [comment]
https://github.com/webpack/docs/wiki/webpack-for-browserify-users#external-requires

**Comment by wighawag** [comment]
Cool, but as mentioned in the issue I actually fixed it, hence the "documentation" in the title as this might help others to know they need special handling in webpack for it to work. If you do not feel like adding any doc on that, at least that issue might help others :)

**Comment by alcuadrado** [comment]
I think this should be fixable in `rustbn.js`. If you can replace the `fs` module for `null` without breaking, it may not be necessary in the first place. 

According to [this doc](https://emscripten.org/docs/api_reference/Filesystem-API.html), you can use an emscripten flag to emit code without the `fs`. module, but I've never used emscripten myself.

Do you know more about this, @s1na or @holgerd77  ?

**Comment by holgerd77** [comment]
No follow-up, will close. Feel free to reopen if this is still an issue.
