### ISSUE TITLE
npm run tslint fails due to postfix operator (!)

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#640]
Our CI does not run `tslint`, I caught it by running manually. 

This is the line mentioned by the script: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/index.ts#L113

```
$ npm run tslint

> ethereumjs-vm@4.1.1 tslint ./ethereumjs-vm
> ethereumjs-config-tslint

+ exec tslint -p ./tsconfig.json -e 'node_modules/**/*' -e '**/node_modules/**/*' -e 'dist/**/*' dist/exceptions.d.ts dist/index.d.ts dist/runBlock.d.ts dist/runBlockchain.d.ts dist/runCall.d.ts dist/runCode.d.ts dist/runTx.d.ts lib/exceptions.ts lib/index.ts lib/runBlock.ts lib/runBlockchain.ts lib/runCall.ts lib/runCode.ts lib/runTx.ts
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.

ERROR: ./ethereumjs-vm/lib/index.ts:107:37 - Remove this unnecessary not-null assertion.

```

It would be great if @s1na could give some feedback :). Then we can fix and add `npm run tslint` in the CI script.

**Comment by s1na** [comment]
Yeah I raised https://github.com/ethereumjs/ethereumjs-config/issues/19 a while back, but didn't get a chance to investigate why it's not being run. I think `tslint` is not being run in most repos.

Hm, `this._common.hardfork()` can potentially be null, so not sure about the error message. But I guess we could do `this._common.hardfork() || defaultHF` to silence it.

**Comment by evertonfraga** [comment]
Great, thanks!

I will keep an eye on this issue. will try to fix before the monorepo migration.

**Comment by holgerd77** [comment]
@evertonfraga What's the state of this issue?

**Comment by evertonfraga** [comment]
Fixed :)
