### ISSUE TITLE
Blockchain in user browsers

### ISSUE THREAD

**Issue by startupgurukul** [ethereumjs/ethereumjs-vm#643]
Hello folks please bear this question has a philosophical bend. 

So current state of ethereum has been use it and price to create apps is proportional to data saved which is dependent on today's ether price. So to take an example we wanted to issue Certificates on ethereum but to save a simple dictionary of name and some more details it costed us way too it's not economically viable ( we ended up saving the certificate on ipfs)

Blockchain has a definite future and it's supposed to change how transparency works and how govt functions how tax payers money moves around etc etc but that never happened. That's because of greed. I know people who were like Rishi's (Indian word for people who can stay away from material desires) got sucked into the riches of crypto. 

Coming to the solution, is it possible to create a network that's lives in users browsers and accessible to anyone with x $ per Y MB  like how the cloud providers charge. This will truly democratise what blockchain was meant to be. 

We are planning to get students to build apps for the govt and use collective Intelligence to bring transparency as well as bring down govt spending. 

The only problem is deploying it, a private node means the whole point of blockchain is lost, but thanks to this repo it can run in a users browser and now there is a possibility of running it on Citizens phone(opt in) there by making it tamper proof, what's you advise on that. 

Thanks in advance.

**Comment by alcuadrado** [comment]
Hey @startupgurukul! I'm glad you find this project useful.

I'm afraid this is not the best place to ask for help with what you are trying to do. This project is focused on implementing the VM, but not so much about deploying your own network. I guess the best place may be https://ethresear.ch/

(I'm leaving this open for now, as maybe another team member has more info)

**Comment by startupgurukul** [comment]
Sure, sorry if it came out like I am asking how to deploy the network

My query is, if you js ethereum is a good usecase for that and as the creators or the lib what do you think about the thought.

**Comment by holgerd77** [comment]
No further additions from other team members, will close here.
