### ISSUE TITLE
NPM: republish packages to the scoped packages

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#655]
- NPM organization access
- Listing packages: 144
- [Migration script](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/republish-npm-packages.sh) — republish identical sources with new scoped format `@ethereumjs/account`

Edit: preparatory steps above were already taken.

- [x] @ethereumjs/account
- [x] @ethereumjs/block
- [x] @ethereumjs/blockchain
- [x] @ethereumjs/common
- [x] @ethereumjs/tx
- [x] @ethereumjs/vm

- [x] replicate the same deprecation messages ([example](https://www.npmjs.com/package/ethereumjs-tx/v/1.2.2))

**Comment by evertonfraga** [comment]
I created [this shell script](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/republish-npm-packages.sh) to make a semi-automated package renamer. 

It downloads tarballs from npm, renames the package in `package.json`, packs and republishes them to the new name. 

I took special care to not have shared state across the loop. As the OTP is needed for every publish, it is the ideal moment to do additional manual checks.

Here's the result of a test run: https://www.npmjs.com/package/@evtest/account-1. Unfortunately we can't use the `shasum` to verify that files are the same, just because resulting `package.json` is different.

You should run the script with the command below, changing the destination package name:
```bash
./republish-npm-packages.sh ethereumjs-account @evtest/account-1
```

This is not a PR, but I'd like to request some additional review.

So far, so good 👌.

**Comment by evertonfraga** [comment]
@holgerd77 @ryanio

**Comment by holgerd77** [comment]
Had a look through your script, this looks good, also manually tested selected commands.

Some notes:

- This `-1` postfix on the name is likely to be removed?

Ah, that's already it. 😄 Side note: you should eventually put your test publication package down again, this has already > 1.000 downloads?

Also tested the install of the test package, worked, the library is also accessible from the Node console:

```shell
$ node
> const Account = require('@evtest/account-1').default
undefined
> const a = new Account()
undefined
> a
Account {
  raw:
   [ <Buffer >,
     <Buffer >,
     <Buffer 56 e8 1f 17 1b cc 55 a6 ff 83 45 e6 92 c0 f8 6e 5b 48 e0 1b 99 6c ad c0 01 62 2f b5 e3 63 b4 21>,
     <Buffer c5 d2 46 01 86 f7 23 3c 92 7e 7d b2 dc c7 03 c0 e5 00 b6 53 ca 82 27 3b 7b fa d8 04 5d 85 a4 70> ],
  _fields: [ 'nonce', 'balance', 'stateRoot', 'codeHash' ],
  toJSON: [Function],
  serialize: [Function: serialize],
  nonce: [Getter/Setter],
  balance: [Getter/Setter],
  stateRoot: [Getter/Setter],
  codeHash: [Getter/Setter] }
```

I'm still grabbing my head a bit around it: do we actually need to republish all the old versions? We don't have a great history within EthereumJS to support old library versions, so would it eventually also be enough to just start the scoped naming with the upcoming releases? Not trying to convince here, just thinking and trying to get a broader picture.

**Comment by evertonfraga** [comment]
Thanks for the feedback! 

Assessing the risks of the migration, one of the worst case scenarios would be to have projects using **outdated references**. If a project uses, let's say, `ethereumjs-account@1.0.3`, and they decide not to migrate to `@ethereumjs/account@3.0.0` — which is fair due to the obvious breaking changes — it will certainly miss any backports or security fixes that we could make to minor/patch versions (eg: `@ethereumjs/account@1.0.4`).

Instead of being selective of which versions would be worth to put in scoped packages (eg: from mid-2018 onwards), it seemed consistent to me to put them all. It also feels good to have a single source of truth :)

After all packages are uploaded, we could emit deprecation notices with npm (`npm deprecate ethereum-account@1.0.3 [message]`) and every time these old versions are installed, the arbitrary message will appear, aiming to spark their respective package.json changes.

**Comment by evertonfraga** [comment]
> Side note: you should eventually put your test publication package down again, this has already > 1.000 downloads

I have no idea where these downloads came from — or if `npm` is even reliable for those kind of metrics. I'll take them down anyway.

**Comment by holgerd77** [comment]
@evertonfraga Yeah, your reasoning (on the transition of all versions) definitely makes sense. We didn't have that much cases of older release patches lately, but that might change in the future. Also the single-point-of-truth consistency argument really weights strongly here.

Yes, deprecating via `npm deprecate` likely makes this complete and will help to get people switching.

**Comment by evertonfraga** [comment]
Right. So I will test more with different libraries and will publish at least one library to @ethereumjs today.

**Comment by holgerd77** [comment]
@evertonfraga Ok, so be it. 🙂 Would say the `ethereumjs-account` library is always a good candidate for stuff like that (not so extensive and limited external use).

Do you subsequently also plan to re-publish all releases as tagged releases on the VM repository together with the release notes (might be overblown, not sure?)? Or will the release notes just reside in the transferred `CHANGELOG.md` file?

**Comment by evertonfraga** [comment]
That is still up for debate. But that would only happen after the migration, so we can create the git tags accordingly.

**Comment by evertonfraga** [comment]
- All scoped packages republished.
- The deprecation notices from `ethereumjs-tx` were replicated in `@ethereumjs/tx`.

![image](https://user-images.githubusercontent.com/47108/77471225-483cb600-6de8-11ea-8e6b-aa677b371d9a.png)

- [@ethereumjs/account](https://www.npmjs.com/package/@ethereumjs/account)
- [@ethereumjs/common](https://www.npmjs.com/package/@ethereumjs/common)
- [@ethereumjs/blockchain](https://www.npmjs.com/package/@ethereumjs/blockchain)
- [@ethereumjs/block](https://www.npmjs.com/package/@ethereumjs/block)
- [@ethereumjs/tx](https://www.npmjs.com/package/@ethereumjs/tx)
- [@ethereumjs/vm](https://www.npmjs.com/package/@ethereumjs/vm)

**Comment by evertonfraga** [comment]
Unfortunately, there has been some caveats from my former approach of republishing all packages as scoped, that include code bloat. A project's `node_modules` would end up having both `@ethereumjs/block@1.0.3` and `ethereumjs-block@1.0.3`, depending on the dependency tree. NPM can't dedupe that for us.

![image](https://user-images.githubusercontent.com/47108/78161278-358f3600-7413-11ea-980e-41dcf68af35d.png)


As major bumps inevitably require care from project maintainers, I propose this:

[With the upcoming major bumps](https://github.com/ethereumjs/ethereumjs-vm/issues/681) on barely half of the monorepo packages (`vm`, `block` and possibly `blockchain`), I'd like to state that's a great opportunity for a scoped packages switchover, major-bumping the remaining libraries as well.

**Comment by holgerd77** [comment]
@evertonfraga Yes, that makes sense.

We can eventually have a look if we integrate low-hanging-fruit respectively urgent breaking updates to libraries if that makes sense on this occasion. But shouldn't overload here either.

**Comment by evertonfraga** [comment]
Thanks!

**Comment by evertonfraga** [comment]
Closing here. Still being tracked on https://github.com/ethereumjs/ethereumjs-vm/issues/671
