### ISSUE TITLE
Preserving git history for the monorepo

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#657]
Our commits are 100% preserved during migration, but once we move files to `./packages/<name>`, GItHub will fail to display full history for files, as they use the result of `git log <file>` on their UI.

GitLab, in turn, uses `git log --follow`, which shows the full contributions to those files, as it tracks files that got moved.

This is a known issue and people are a bit disappointed with GitHub for that (https://github.com/isaacs/github/issues/900). The good news here is if/when GitHub implements that, it will display full history in a backward compatible way.

One possible option is to use `lerna import` to rewrite all commits as if files always lived under `./packages/<name>`. That preserves contributors shown on GitHub, but that can cause a lot of trouble for fork repos, given this also changes the commit hashes.

My hunch is to communicate this well on README, explaining that this is a trade-off to keep the tree with the same commit hash, facilitating for other projects to keep up with ethereumjs repos. And again, if/when GitHub implements that, the problem will be solved.

**Comment by evertonfraga** [comment]
Live example: 
- [GitHub](https://github.com/evertonfraga/ethereumjs-vm/commits/monorepo/packages/vm/README.md) - no history
- [GitLab](https://gitlab.com/evertonfraga/ethereumjs-vm-monorepo/-/commits/monorepo/packages/vm/README.md) - full history

A reminder that this is a front-end thing only, and if any user performs `git log --follow README.md` will get the result below:
![image](https://user-images.githubusercontent.com/47108/74274128-9174f280-4cdf-11ea-977c-48a53d5473e6.png)

**Comment by alcuadrado** [comment]
> That preserves contributors shown on GitHub, but that can cause a lot of trouble for fork repos, given this also changes the commit hashes.

The other option preserves hashes of both repos? Or just `-vm`'s?

**Comment by axic** [comment]
I would advise against changing hashes and would suggest to use proper `git mv` and hope that at some point Github sorts its problem out (even though I have been subscribed to the issue for the past 2.5 years).

**Comment by holgerd77** [comment]
@axic Yes, would very much agree here.

**Comment by evertonfraga** [comment]
@axic yes, our script uses [`git mv`](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/monorepify.sh#L62) to move files under `./packages/` and adds all commits with their respective histories and hashes to the monorepo, with [`git merge … --allow-unrelated-histories`](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/monorepify.sh#L110).

**Comment by evertonfraga** [comment]
@alcuadrado 
> The other option preserves hashes of both repos? Or just -vm's?
It preserves hashes for all repos in the current solution.

**Comment by alcuadrado** [comment]
I'd go forward with your script and `git mv`.

**Comment by evertonfraga** [comment]
Thanks for the input, everyone. The execution is in place.
