### ISSUE TITLE
Monorepo: migrating releases

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#667]
- [x] Publish all `git tags` in the new format (`@ethereumjs/account@1.0.3`), from all packages
- [ ] Migrate VM releases
  - [ ] point releases to new tags
  - [ ] delete old tags
- [ ] Import releases from other repos
    - [ ] point to tags to the new format
    - [ ] add a note _"originally released in: xxxx-xx-xx"_
    - [ ] import them in chronologic order

**Comment by evertonfraga** [comment]
I just published [all packages tags](https://github.com/ethereumjs/ethereumjs-vm/tags), and the [Changelog links](https://github.com/ethereumjs/ethereumjs-vm/compare/@ethereumjs/vm@4.1.1...@ethereumjs/vm@4.1.3) are working as intended.

**Comment by holgerd77** [comment]
@evertonfraga 👍 I thought it would maybe nice to copy-over the release notes to the [releases page] at least for the respective last release of each library, what do you think (or should we even take the time and copy over all notes)?

**Comment by evertonfraga** [comment]
I was planning to migrate all historical releases to the releases page, so we could link them to the respective tags I created today and be the historical reference point for library changes.

I will still use the playground monorepo to test these releases.
