### ISSUE TITLE
Gas cost for ether transfer < 9000

### ISSUE THREAD

**Issue by hacker-DOM** [ethereumjs/ethereumjs-vm#678]
According to the Yellow Paper, creating a transaction costs 21000 gas (regardless if it contains value) and creating a message call with non-zero call value costs at at least 9000 gas. Yet when I call Contract's default function in Remix (uses ethereumjs-vm) with a value of 1 ether, the entire transaction costs 28562. That means 7562 for execution. How could it be less than 9000?

```
pragma solidity ^0.5.0;

contract Helper {
    function () external payable {}
}

contract Contract {        
    function () external payable {
        [insert helper address here].transfer (1 ether);
    }
}
```

I'm on Remix@0.9.4, which uses `ethereumjs-vm@4.1.3`.

**Comment by alcuadrado** [comment]
Hey @hacker-DOM,

From your explanation, I assume that you aren't sending any data in your tx, that would explain the lower-than-expected gas cost.

**Comment by holgerd77** [comment]
Will close here, let us no if the comment from @alcuadrado above is not explaining your issue.
