### ISSUE TITLE
Replace defineProperties with explicit type-safe alternative

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#683]
After the [transition](https://github.com/ethereumjs/ethereumjs-account/pull/27) to typescript, a possible improvement would be to replace `defineProperties` which defines attributes on the class implicitly with a more explicit type-safe alternative. Note that `defineProperties` is used in other repositories as well, and the solution should take this into consideration.

**Comment by holgerd77** [comment]
Alternative approach to completely remove `defineProperties` suggested in https://github.com/ethereumjs/organization/issues/56 which supersedes this issue and is already been executed on e.g. along the tx library refactor in #812 

Will close here.

**Comment by jochem-brouwer** [comment]
Just found an error in #849 which has to do with this. 

There's a block RLP header dumped in `BLOCK_difficulty_GivenAsList_Frontier` where the `difficulty` is (after `rlp.decode`): `[ <Buffer 02>, <Buffer 00>, <Buffer 00> ]` which is a list, thus of wrong type, and should throw. However, in `header.ts` we use `defineProperties` which for some reason converts this list to `<Buffer 00 00 00>`

**Comment by holgerd77** [comment]
@jochem-brouwer when working on the block library lately I realized that this library is very much due for a refactor as well like the tx library, somewhat hesitant to add this to v5 as yet another task, but maybe we should go this extra mile, have the impression that this is a somewhat substantial factor for lower reliability in the whole library suite and also somewhat hinders further development and improvements on everything "block" related.

Not sure. 🤔

//cc @ryanio

**Comment by holgerd77** [comment]
(One other think beside removing `defineProperties` is this strange non-inheritance-usage for `Header` -> `Block` and just manually calling the header class from block on various occasions)

**Comment by jochem-brouwer** [comment]
Yes, about this refactoring: I have glanced over @ryanio's work for Tx and it seems that similiar jobs have to be done on Block as well. I was about to propose we'd also need a refactor for block (and we might take a look at the other packages aswell).

**Comment by holgerd77** [comment]
*sigh* yes, than maybe let's take `Block` in here 🙂 , from the other libraries `Account` is also a similar candidate. The library is not that big so we should do as well.

(`Blockchain` is another scope and even though there are likely suboptimalities as well this would go beyond a manageable scope, especially since we are all still somewhat "away" from this library. I think we'll collect more experiences there when starting to work on the client and can evolve this library over time and at some point eventually follow-up with a breaking release there as well)
