### ISSUE TITLE
Deprecating blockFromRpc and blockHeaderFromRpc

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#686]
I'm working on migrating this library to TypeScript, and in doing so, I found about `blockFromRpc` and `blockHeaderFromRpc` functions. 

This struck me by surprise, as this is the only core ethereumjs library that has anything to do with the Ethereum RPC. They feel kinda out of place to me and haven't been updated in two years, so I wonder if we should deprecate/remove them. Also, they aren't super complex functions that can't be maintained somewhere else.

I'd like to know what consumers of these think, so I [searched for them on github](https://github.com/search?q=blockFromRpc&type=Code). It looks like the main consumers are MetaMask and Musteka-la. There are also multiple forks of this library for other blockchains, but those won't be affected by this.

Would you mind giving a quick answer here @kumavis @dryajov ? Thanks!

**Comment by kumavis** [comment]
if you move them out, make sure you respect semver and publish as a major version

**Comment by holgerd77** [comment]
No follow-up for quite some time, functionality is now also used internally for the VM `mainnetBlocks` benchmark, so there is some usage and also no pressing demand for removal.

Will close here.
