### ISSUE TITLE
Peculiarity in how getBlocks skips blocks

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#698]
Discovered this when reviewing the skip related tests in ethereumjs/ethereumjs-blockchain#134. Either the name is extremely confusing or there's a bug in how `getBlocks` handles skips. I'd assume it would skip `n` blocks from the beginning (another question is whether it should include the genesis block). But it skips a block every `n` block, e.g. if `n=1`, then it returns blocks `[genesis, 2, 4, 6, ...]`. Here's the code that needs to be fixed:

https://github.com/ethereumjs/ethereumjs-blockchain/blob/0cf409e8c5d9f9e36a2d1ef7d584dafeafae35d3/src/index.ts#L669-L671

**Comment by jochem-brouwer** [comment]
We should not remove this, because, as mentioned, this is part of `GetBlockHeaders` spec of the ETH protocol.

**Comment by holgerd77** [comment]
Seems to be solved along discussion, will close for now, feel free to re-open if still considered as an issue.
