### ISSUE TITLE
Performance in Browser

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/ethereumjs-vm#7]
from wanderer/node-ethereum/issues/16
```
contract c {
    uint[] data;
    function f() {
        for (uint x = 0; x < 1000 ; x++)
            data[data.length++] = x;
    }
}
```
run inside the browser will stall it (inluding all other tabs) for several minutes. Changing the loop into an infinite loop (and providing 3000000 gas) will make it even worse and crash most of the browsers.
It would be good to know whether this also happens for node.

**Comment by kumavis** [comment]
nice find -- i intend to run the vm in a worker and that should help with the ui blocking, but yeah-- perf

**Comment by wanderer** [comment]
A big part at least in the browser; is the trie. It has to do all the sha3 ops in pure JS

**Comment by wanderer** [comment]
we have since stoped using the merkle trie in the browser. I'm going to close this for now, or until we have benchmarks
