### ISSUE TITLE
runCode callback value has exception: 1 iff there is no exception

### ISSUE THREAD

**Issue by chris-martin** [ethereumjs/ethereumjs-vm#70]
This is what `runCode.js` looks like now:

```js
exception: err ? 0 : 1
```

It seems to me that this logic is backwards, and should be

```js
exception: err ? 1 : 0
```

But I'm also not sure why it isn't a boolean, as the documentation says it should be.

```js
exception: !!err
```

44d096a fixed this and closed #48, but then it got reverted. I can't tell why.

**Comment by chris-martin** [comment]
This comment may explain the revert: https://github.com/ethereumjs/ethereumjs-vm/pull/49#issuecomment-199802584

**Comment by wanderer** [comment]
`exception: err ? 0 : 1`
Yeah this is just a weird thing in the Spec. The reason it was reverted was because when a call traps a `1` is supposed to be pushed to the stack. And if the exuction doesn't fail a `0` gets pushed to the stach

**Comment by chris-martin** [comment]
Is this supposed to be like a process exit code, where a nonzero value indicates failure? If so, the readme needs to be fixed, because it says `exception` is

> a `boolean`, whether or not the contract encountered an exception

**Comment by wanderer** [comment]
> Is this supposed to be like a process exit code, where a nonzero value indicates failure? 

yep exactly! Could you update the readme?

**Comment by chris-martin** [comment]
But it's still backwards, right?

> when a call traps a 1 is supposed to be pushed to the stack. And if the exuction doesn't fail a 0 gets pushed to the stach

That's not what it does. If it fails, it's `0`, and if it doesn't fail, it's `1`.

**Comment by wanderer** [comment]
I'm confusing myself here :P so lets look at the yellowpaper 

> μ'ₛ[0] ≡ x
where x = 0 if the code execution for this operation failed due to an exceptional halting

 μ'ₛ[0] is the item that is placed onto the stack
