### ISSUE TITLE
Add EIP-centric API

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#700]
Following AllCoreDevs discussions regarding scope definition for hard forks, I believe we should incorporate EIP-centric options/querying ala [`gteHardFork`](https://github.com/ethereumjs/ethereumjs-common/blob/9e624f86107cea904d8171524130d92c99bf9302/docs/classes/common.md#gtehardfork).

I need some time to think about the specifics but wanted to raise the concern here.

**Comment by holgerd77** [comment]
Addressed by #856 (and following PRs).

Will close.
