### ISSUE TITLE
We might need to fix the "files" option in package.json (?)

### ISSUE THREAD

**Issue by danjm** [ethereumjs/ethereumjs-vm#701]
I've experienced a problem when npm installing `ethereumjs-common` and `ethereumjs-util` in both the `ethereumjs-vm` and `ethereumjs-tx` repos. The node_modules directories of common and util both seem to install differently when the `dist/` path within the `"files"` prop of `package.json` is provided with and without the trailing slash.

This first occurred when I was trying to point package.json of the vm to a specific commit of common (while working on the constantinople fix). In that case, the dist directory of `node_modules/ethereumjs-common` was not installing / was non-existent.

Just recently I noticed that ethereumjs-tx had the wrong version of `node_modules/ethereumjs-util/dist/index.js` even though the correct version was listed in `node_modules/ethereumjs-util/package.json`

In both cases, it seems that switching
```
  "files": [
    "dist"
  ],
```
to
```
  "files": [
    "dist/"
  ],
```

corrects this problem. This was only based on me pointing to the local repo from the tx package.json. Before making such a change, I want to confirm it is compatible across major operating systems.

This may be OS or npm or node version related. I will continue to investigate, but wanted to share in case others have noticed anything similar or know of proper solutions.

**Comment by evertonfraga** [comment]
@danjm should you have any considerations, please reopen this issue.
