### ISSUE TITLE
Accepts 39 character addresses

### ISSUE THREAD

**Issue by jafri** [ethereumjs/ethereumjs-vm#704]
There appears to be a tolerance in the address fields to accept 39 character fields, instead of enforcing 40 characters

For example, both of these are valid in the library

0xf79b834a37f3143f4a73fc3934edac67fd3a01c
0xf79b834a37f3143f4a73fc3934edac67fd3a01cd

**Comment by ryanio** [comment]
Resolved in #812 with the new [Address](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/classes/_address_.address.md) class that enforces an [exact length](https://github.com/ethereumjs/ethereumjs-util/blob/master/src/address.ts#L16).
