### ISSUE TITLE
Breaking up the Transaction class

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-vm#709]
Created this issue to continue the discussion started in ethereumjs/ethereumjs-tx#142 and to garner feedback whether you think this'd make sense. Here's a rough sketch of one (non-breaking) approach that comes to my mind:

Make [TxData](https://github.com/ethereumjs/ethereumjs-tx/blob/master/src/types.ts#L24) a class, and use it to store the actual data for the transaction, plus methods for serialization/deserialization. In `Transaction`'s constructor instantiate `TxData` and store it for later use (possibly add a `static fromTxData` method). Logic methods stay on `Transaction` and use `TxData` as source of data but do not mutate it.

If this is too vague I can try to write up (or a diagram) of something more concrete. Please feel free to propose other ideas.

**Comment by ryanio** [comment]
Resolved with #812
