### ISSUE TITLE
Signing data returns wrong signature

### ISSUE THREAD

**Issue by sc0Vu** [ethereumjs/ethereumjs-vm#710]
Hi,

Thanks for this great library. Recently I try to sign transaction, it returned signature with wrong length (r: 31 bytes, s: 32 bytes). After debug deeply, found out that if the first bytes is 0, the library will remove.

Data:
```Bash
// signature from ecsign, length of r is 32
{ r: <Buffer 00 18 16 2b ...... 45 a8 e8>,
  s: <Buffer 0d 25 7b ...... 89 f8 a0>,
  v: 27 }

// signature from ethereumjs-tx, length of r is 31
{ r: <Buffer 18 16 2b ......  45 a8 e8>,
  s: <Buffer 0d 25 7b ...... 89 f8 a0>,
  v: 27 }
```

Do you have any idea about this?
Thanks!

**UPDATE by @alcuadrado: These two signatures are valid. They are equivalent when RLP-encoded, and that's how the Ethereum network sees them. This is currently (2019-05-10) a known limitation of this library, it trims all leading zeros of `r` and `s`.**

**WORKAROUND: You can transform `r` and `s` into big ints before comparing them.**

**Comment by ryanio** [comment]
This should now be resolved in #812 by storing R & S as `BN`.
