### ISSUE TITLE
Leading zeros are stripped from signature values

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#711]
I'm opening this issue mainly to document some unexpected behavior in this library: When signing a transaction, the `r` and `s` values get their leading zeros removed.

This behavior doesn't invalidate the signatures, but can make comparing them non-obvious, as using `Buffer.prototype.equals` can give false negatives. As a workaround, [ethereumjs-util's stripZeros](https://github.com/ethereumjs/ethereumjs-util/blob/v6.1.0/src/index.ts#L150) can be used before comparing the `r` and `s` buffers:

```js
function areSignatureBuffersEqual(buffer1, buffer2) {
  return stripZeros(buffer1).equals(stripZeros(buffer2))
}
```

The root of this behavior is that this library's internal representation mimics the protocol-level rlp-encoded transaction representation. This [is being reevaluated](#151) and may change in a future major version.

**Comment by ryanio** [comment]
This should now be resolved in #812 by storing R & S as `BN`.
