### ISSUE TITLE
question about "hash(false)" when "chainId" > 0

### ISSUE THREAD

**Issue by warren-bank** [ethereumjs/ethereumjs-vm#712]
hello. please correct me if I'm wrong, but my understanding of [EIP 155](https://github.com/ethereum/eips/issues/155#issuecomment-318205104) is that the raw data Array that gets hashed should contain the value `0` for the fields: `r` and `s`.

in looking at your implementation of the `hash()` function, it also _appears_ that's what is [intended](https://github.com/ethereumjs/ethereumjs-tx/blob/dab647f12775118bd5b235797e73715ec4ddd5e7/index.js#L158).

however, in testing the result.. I'm seeing that these fields are being set to empty (unallocated, zero-length) Buffers.

here's a demo (based mostly on the example in the README)..

```javascript
const EthereumTx = require('ethereumjs-tx')
const privateKey = Buffer.from('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')

const txParams = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
  // EIP 155 chainId - mainnet: 1, ropsten: 3
  chainId: 3
}

const tx = new EthereumTx(txParams)
tx.sign(privateKey)

let raw = tx.raw
tx.hash(false)  // bit of a hack: "raw" contains updated {v,r,s} from "items"

console.log(raw.slice(6))  // print the last 3 fields: [v,r,s]
```

__output:__

```javascript
[ <Buffer 03>, <Buffer >, <Buffer > ]
```

What's really odd (to me) is that both of these fields are marked ["allowZero"](https://github.com/ethereumjs/ethereumjs-tx/blob/dab647f12775118bd5b235797e73715ec4ddd5e7/index.js#L88). So, without tracing the code in much depth, it would seem that the setter for these fields should allow the assignment to `0`.

Is this a bug?

**Comment by ryanio** [comment]
This should now be resolved with #812. Please use the new `tx.getMessageToSign()` in place of `tx.hash(false)`.
