### ISSUE TITLE
Should verifySignature really verify signature?

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/ethereumjs-vm#713]
Right now method [verifySignature](https://github.com/ethereumjs/ethereumjs-tx/blob/a73cc663b6f46b995a9b1be1e18ac8dc4d89d2f0/index.js#L207) just restore public key from signature, but does not really verify that restored public key corresponds to private key which was used for signing transaction. Should we restore public key and then verify signature with it right after?

**Comment by holgerd77** [comment]
@ryanio eventually you can update the description of the test mentioned above with something more fitting along your work on #812, will otherwise follow the recommendation and close here.
