### ISSUE TITLE
Documentation: Add used unit as comment to examples

### ISSUE THREAD

**Issue by JohannesMayerConda** [ethereumjs/ethereumjs-vm#715]
I saw the README and the index.md under docs with their examples but I'm not completely sure about the units. It has been asked on [ethereum.stackexchange](https://ethereum.stackexchange.com/questions/41935/when-constructing-a-transaction-what-is-the-unit-of-the-value-field)  what the unit of the value field is. And I am currently not 100% sure what unit the gas limit and gas price is.

A simple comment in the README.md about what number in what unit the gasPrice, gasLimit and value is would help people understand the code and avoid mistakes...

**Comment by holgerd77** [comment]
No follow-up, will close.
