### ISSUE TITLE
[Berlin] EIP-2537: BLS12-381 Curve Operation Precompiles

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#738]
Not to be underestimated, this is a pretty big one (likely).

Might be a way to follow the path of the [rustbn.js](https://github.com/ethereumjs/rustbn.js) library and do an analogue integration on the [ZCash implementation](https://github.com/zcash/librustzcash/tree/master/pairing).

Eventually it is also possible (not sure about the performance implications) to take a pure JS implementation from the list of suggestions in the [EIP specification](https://github.com/ethereum/EIPs/pull/2537/files#diff-629a64fd292614a3917c7fb9a32f9337R290).

Discussion around this should start relatively imminent so that we can have some decision here.

**Comment by holgerd77** [comment]
Thought about this a bit more, especially on the question which library to use: the integration of a library itself is actually not that much work - just some simple API calls - see e.g. the implementation for an exemplic [rustbn.js](https://github.com/ethereumjs/rustbn.js) precompile like [evm/precompiles/ecadd.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/evm/precompiles/06-ecadd.ts).

So I think we can very well start with a JS library integration RIGHT NOW (one, but not necessarily THE candidate to investigate [Apache Milagro](https://github.com/apache/incubator-milagro-crypto-js)) and in parallel further prepare around a potential Rust-bindings implementation.

I have a growing sympathy for this solution since this would:

- substantially speed things up (respectively not delay things too much 😋)
- allow us to at least ship a minimal working solution if we won't get it managed to release a Rust version in time (so kind of a backup plan, at least to have something here would be 1000x (Scientific Estimation [tm] 😄) better than nothing at all, so that people can do some experimental runs in time)
- allow us to get some better feeling on the sideline for the JS side-of-things performance

So again, think this won't cause a substantial amount of extra work, respectively THE extra work it is causing should be very much limited and justifiable by the extra benefits.

What do you think?

**Comment by jochem-brouwer** [comment]
Heya, small update. I've checked this Apache Milagro repository but to me it does not seem that they expose the low-level curve operations which we need. Instead, [mcl-wasm](https://github.com/herumi/mcl-wasm) seems (so far) to look more promising.
