### ISSUE TITLE
Filter label for generic issues

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#741]
It would be nice to have a way to filter for the generic issues along the line of the "package:*" labels, these fall between the cracks right now.

I would suggest a "package: monorepo" label or - simplified, maybe cleaner - "monorepo", in the same color as the other labels.

Maybe to consider/question: might there be any side effects on automated scripts/actions here if we add?

**Comment by holgerd77** [comment]
//cc @evertonfraga If you are reading this and find it a good idea, maybe directly add the label in the flavor of your choice to the labels and un-labelled issues if you want and close the issue here.

**Comment by evertonfraga** [comment]
I agree, I felt the need of some way to categorize general/monorepo issues as well.

**Comment by holgerd77** [comment]
Ok, I'll give this a simple label `monorepo` now. Just had a quick look, all unlabeled issues fit into this and context is also becoming clear enough by having this in line with the other `package:*` labels.

**Comment by holgerd77** [comment]
Update: ah, actually I will not 😝, since sorting is getting out of order - just realized - and this will render half-useless if not clustered together with the other `package:*` labels, so will take `package: monorepo` instead.

At the end main thing is to have the filter-possibility anyhow.

**Comment by holgerd77** [comment]
Ok, added the new `package: monorepo` label and once went through the issues and completed labelling on unlabeled-`package: *`-issues, should have gotten the all now, see [filter view](https://github.com/ethereumjs/ethereumjs-vm/issues?q=is%3Aopen+is%3Aissue+label%3A%22package%3A+monorepo%22) on open issues.

Will close here.
