### ISSUE TITLE
Add interface for third-party StateManager implementations

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#742]
Part of #681 

Will give this its own issue in case there is some further need for discussion and last clarifications here around this.

`StateManager` currently residing [in the VM package](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm/lib) in the `state` subdirectory should get its own package under `packages/statemanager` (is this lower-case naming the way to go?) and released separate from the `VM` releases.

Code in the `VM` has to be adopted accordingly and tests and docs need to be moved along.

**Comment by alcuadrado** [comment]
I'm a little late to the party, but why a separate package? Wouldn't an interface in `-vm` be enough for people to be able to replace it?

I'm actually thinking about having two separate `StateManager`s in Buidler EVM, and I don't see the need for it to be a separate package.

**Comment by holgerd77** [comment]
Not totally against it but I would still prefer a separation, some arguments:

- This would make an API more robust (I would argue) and and API changes more explicitly exposed through major version updates on the separate repo
- People could do their own forks of the repo and build their `StateManager` implementations upon, otherwise they would need to manually copy-paste the code
- No extra dependencies are drawn in if people just want to use a VM with their own `StateManager` (e.g. without MPT), so this improves on modularization

But - again - we can get this a bit into discussion. Some arguments here might be some, some less valid or relevant.

**Comment by holgerd77** [comment]
//cc @s1na Do you have got any opinion here?

**Comment by s1na** [comment]
No strong opinion. But overall agree with Pato that it's not strictly necessary. However if some use-cases came forth why not!

**Comment by alcuadrado** [comment]
I don't have a strong opinion either @holgerd77. I was just curious.

> No extra dependencies are drawn in if people just want to use a VM with their own StateManager (e.g. without MPT), so this improves on modularization

This is very interesting. I'm not sure how this would be achieved though. Where would the interface of StateManager be defined? In the VM package? Cause if it's defined in the StateManager package, you do need to pull all of its dependencies.

**Comment by holgerd77** [comment]
@alcuadrado didn't thought about an interface yet TBH, just thought that people would just take the `StateManager` package as the reference implementation, have a look at the API and do their own implementation along (not saying this is the best way, this was just my state of thinking since this is I guess how it is done today).

Not sure, would it be a good pattern to release just the interface within its own package and then have different state manager implementations (including our own) to pull this in from there? Think this would decouple things? Or is this over-engineered?

Just a first shot, my practical experiences on stuff like that is pretty limited.

Will also circle in @mattdean-digicatapult, the original initiator and persistent implementor over months on giving the `StateManager` a stable API (hi Matthew, how are things going? 😄), maybe he has also a stance on this here.

**Comment by holgerd77** [comment]
@alcuadrado benefits would only come into play though if we enforce people to pass a state manager instance themself on VM initialization and we wouldn't setup the default one if none external is passed.

Just skimming through the initialization code at [index.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/index.ts) a bit together with having a look at the API. Getting sceptical myself here, maybe this is rather a burden than an improvements, also together with the question of how to cleanly pass a unified `Common` instance on both the `StateManager` and the `VM`.

So not sure. Maybe it would also suffice here if we rather stick with the status quo + eventually add an interface for `StateManager` on the VM side?

**Comment by mattdean-digicatapult** [comment]
Hi @holgerd77, things are going well; I've just been working on other projects.

When doing the original `StateManager` work my intent was for it to be externalized at some point to a separate package. I felt the implementation in repo was quite opinionated and other use-cases for implementing a custom `StateManager` were apparent. Much more important for me back then though was to have a stable `StateManager` interface to work against.

That said, whilst this version is the primary one used by the community there seems little benefit to moving it to an external module as long as the interface is exposed and maintained. If, at some point in the future, an alternative implementation gets some traction then that would be the time to look at pulling the module out more aggressively (maybe).

My inkling then would be to look at defining an interface for `StateManager` much like I did informally (back when this was all js) in the original work. That way if someone wants to make an alternative interface they can do so safely. As to where it goes; for now probably leave it in the `VM`?

**Comment by holgerd77** [comment]
Hi @mattdean-digicatapult, thanks for the quick assessment, that helps a lot!

I guess since there was already rather scepticism on the proposal to draw this out then we will rather go the way of defining an additional in-VM-interface here to have technically enforced a robust API?

@ryanio do you want to prepare a PR on this since you already worked on the final `StateManager` promisification?

**Comment by holgerd77** [comment]
Taken over by @s1na, please eventually x-coordinate

**Comment by ryanio** [comment]
Completed with https://github.com/ethereumjs/ethereumjs-vm/pull/763
