### ISSUE TITLE
Improve reproducible builds for our CI

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#751]
Oftentimes, someone points that this repo does not have a `package-lock.json`, so they can't make a reproducible build.

Although [we do have a reason for not having package-lock.json in our repos](https://github.com/ethereumjs/merkle-patricia-tree/pull/62#issuecomment-443293041), we can enable people from doing reproducible builds by just making the generated package-lock.json available at build time.

The task is to upload the `package-lock.json` as job artifacts for root repo and each of the six packages.

https://github.com/actions/upload-artifact#upload-using-a-wildcard-pattern

The command below works locally with that glob expression. We need to check if the actions linked above accepts it (probably yes).

```sh
cat {./,packages/*/}package.json
```

// cc: @sz-piotr

**Comment by alcuadrado** [comment]
I've been discussing with a friend about not having `package-lock.json`s lately, and I'm not really sure if that's the best alternative anymore. I was really skeptical about not using them when I first started collaborating here, then completely sold on the idea, and now 🤷🏻‍♂️

My friend's theory is that using package locks, with a service like dependabot or [Renovate](https://renovate.whitesourcesoftware.com/) plus a daily CI run which ignoring package-locks has all the advantages of not using them, plus reproducible builds for PR-based CI runs and easier caching.

**Comment by evertonfraga** [comment]
That’s good to know!

We can take that route. Lerna installs will become faster because it uses `npm ci` internally for CIs

**Comment by alcuadrado** [comment]
You may find this interesting, @evertonfraga https://github.com/actions/cache/issues/323

**Comment by evertonfraga** [comment]
That’s awesome! Thanks for pointing it out @alcuadrado.

**Comment by evertonfraga** [comment]
This is in place.
