### ISSUE TITLE
problem help me gas * price + value

### ISSUE THREAD

**Issue by exnovin** [ethereumjs/ethereumjs-vm#753]
I've seen many topics, but I've yet not solved my problem. Please, help me!

`var EthereumTx=require('ethereumjs-tx').Transaction
 const Web3=require('web3')
 const web3 = new Web3('https://rinkeby.infura.io/v3/85xxxxxxxxxxx2af25e829b8d9df')
 const account1='0xbd77caf08fe49d3f5aef6f83fc23b8d2129b468f'
 const main = async () => {
    const count = await web3.eth.getTransactionCount('0xxxxxxxxxxxxxxxf5aef6f83fc23b8d2129b468f');
    const nonce = web3.utils.toHex(count);
    const block = await web3.eth.getBlock('latest');

  const gasLimit = web3.utils.toHex(3000000)
  const gasPrice = web3.utils.toHex(22 * 1e9) // 5 gwei
 const privateKey = Buffer.from(
  'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  'hex',
)

        const txParams = {
          from: "0xxxxxxxxxxxxxxxxxxxxxxxxxxxx9b468f",
          gasPrice: gasPrice,
          gasLimit: gasLimit,
          to: '0xxxxxxxxxxxxxxxxxxxxxxb91a04e',
          value: web3.utils.toHex(web3.utils.toWei('1','ether')),
          data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
         chainId: '0x04'

        }
// The second parameter is not necessary if these values are used
const tx = new EthereumTx(txParams, { chain: 'rinkeby', hardfork: 'petersburg' })
tx.sign(privateKey)
tx.getSenderAddress(account1)
const serializedTx = tx.serialize()
    const raw ='0x'+serializedTx.toString('hex')
    // broadcast the trasnaction 

    web3.eth.sendSignedTransaction(raw,(err,txHash)=>{
      console.log('err:',err,'txHash:',txHash)
    })
 }

main();`

**Comment by holgerd77** [comment]
Hi @exnovin, it is not really apparent here what your problem actually is, please provide a more accurate description here together with the output from the example, so that someone who wants to trace do not has to replay/reconstruct the whole example with ones own data setup. Thanks!

**Comment by holgerd77** [comment]
No follow-up, will close.
