### ISSUE TITLE
Remove async dependency / Test runner code cleanup

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#759]
The VM still uses the `async` library in the production code in [runBlockchain.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runBlockchain.ts#L3) as well as in the [test runner files](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm/tests) (see also [Developer Documentation](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/developer.md) on test run information).

These occurrences should be replaced by native async code structures, so that the dependency can be removed from the library.

(likely also be able to extend this issue to other libraries, not sure about the usage there as well, but likely it is still used there as well)

Might also be a good occasion to do some further clean-up of the test runner code - if apparent - while working on this.

**Comment by jochem-brouwer** [comment]
It looks like some tests might succeed preliminary (i.e. https://github.com/ethereumjs/ethereumjs-vm/blob/61c3dcaeeb8152f48f023c803aabbc79392ba208/packages/vm/tests/api/state/stateManager.js#L166). I'll fix these tests if they cover the async library. I think cleaning all tests (and checking if the tests are correct) should be a different issue @holgerd77.

CC @evertonfraga

**Comment by evertonfraga** [comment]
That makes sense. 

This particular case is recent and haven't yet made to production, I am grateful that you caught it before it hits npm :)

To prevent these false positive cases, at least for the async scenario, we can replace `test.end()` by [`test.plan(x)`](https://node-tap.org/docs/api/#tplannumber).

**Comment by jochem-brouwer** [comment]
(Writing some notes for myself here but feel free to comment)

I have edited the blockchain package tests which use anything of the async library. I have included `test.plan` for these tests to explicitly check they are (still) correct (and did not run into failing tests =))

**Comment by ryanio** [comment]
completed in #779
