### ISSUE TITLE
Verify V for signature not working with Azure KeyVault generated signatures

### ISSUE THREAD

**Issue by devedse** [ethereumjs/ethereumjs-vm#768]
Hi all, I'm quite new to signing transactions but I'm currently working on implementing signing transactions using an external Signer (in this case Azure KeyVault).

When calling Sign on Azure Keyvault it returns R and S. The V value can be determined with the following formula:

```
const v = ethTx.getChainId() ? recovery + (ethTx.getChainId() * 2 + 35) : recovery + 27
```

However since Azure KeyVault doesn't return Recovery I decided the simplest option would be to just try the values 0, 1, 2, 3 and see which one returns a valid signature.

Reference:
https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v

Once I try the values 2 and 3 I run into the issue that the _validateV code throws an error. As per my investigation a recovery value should be valid if it's 0, 1, 2 or 3. Whereas the code seems to only accept a recovery value of 0 or 1: (It does the same formula as above except only checks for 35 and 36, not 37 or 38).

https://github.com/ethereumjs/ethereumjs-vm/blob/47e8ca187aeede79f7540c0917735431664f0d7e/packages/tx/src/transaction.ts#L351

Is there a reason for this implementation or can we change the code to something like this:
```
  private _validateV(v?: Buffer): void {
    if (v === undefined || v.length === 0) {
      return
    }

    if (!this._common.gteHardfork('spuriousDragon')) {
      return
    }

    const vInt = bufferToInt(v)

    if (vInt === 27 || vInt === 28 || vInt == 29 || vInt == 30) {
      return
    }

    const isValidEIP155V =
      vInt === this.getChainId() * 2 + 35 || vInt === this.getChainId() * 2 + 36 || vInt === this.getChainId() * 2 + 37 || vInt === this.getChainId() * 2 + 38

    if (!isValidEIP155V) {
      throw new Error(
        `Incompatible EIP155-based V ${vInt} and chain id ${this.getChainId()}. See the second parameter of the Transaction constructor to set the chain id.`,
      )
    }
  }
```

**Comment by devedse** [comment]
Hmm, I've done some more investigation and it seems the C# code indeed also returns 0 or 1. I tried about 100 times.

Then it must be another reason why the signature fails to validate. I don't really understand why yet.

**Comment by alcuadrado** [comment]
I'm afraid I know little to nothing about ECC. All I know is that those are always `0`, and `1`, at least in the js side of things.

I bet it's related to this EIP: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md

It reduces the space of possible transaction signatures to avoid malleability attacks, and that probably discards `v = 2` and `v = 3`.

**Comment by alcuadrado** [comment]
This may also be helpful: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol#L46

**Comment by devedse** [comment]
I've done some more work on the code and found out the issue. Apparently I forgot to do some opperations on the S value I got from the KeyVault.

Hopefully once I've finished this all up we can integrate it in the Web3.JS library. :)
