### ISSUE TITLE
Avoid concurrency limit for GH actions

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#776]
It seems @ethereumjs (as opposed to @ethereum) is on the free plan. That gives us merely 20 concurrent jobs. Today we have 27 GitHub jobs for each run in a typical PR. 

We should use the data gathered at https://github.com/ethereumjs/ethereumjs-vm/issues/723#issuecomment-638174429 to make some smart cuts in our CI runs. 

![image](https://user-images.githubusercontent.com/47108/84675430-3a379680-aefa-11ea-808e-bdb93d6a756a.png)
_Source: [GitHub Help](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limits)_.

**Action items**
- [x] Run only one node version per package, instead of four (from 27 to 9 GH jobs)
- [x] Run all supported node versions on master branch, so the remaining node versions will always get tested after merging.

**Comment by holgerd77** [comment]
Closed by #939
