### ISSUE TITLE
Address from CREATE2 is sometimes incorrect, with highest address byte cleared

### ISSUE THREAD

**Issue by haltman-at** [ethereumjs/ethereumjs-vm#777]
Hi,

There seems to be a problem where the `CREATE2` opcode occasionally results in an incorrect address being used for the created contract.  The address is *almost* correct, but its highest byte is zeroed for whatever reason.  Everything else is correct.

Unfortunately, I do not know how to reproduce this problem consistently; it only happens sporadically.  Most of the time the `CREATE2` addresses are correct as expected.  Regardless, I am hoping that you might be able to find a way to reproduce and fix this bug all the same.

Hope that's helpful and thank you!

**Comment by jochem-brouwer** [comment]
Hi there, thank you for submitting this interesting issue!

How did you encounter this problem? You state that the address is almost correct, except the highest byte is sometimes zeroed. How did you figure this out? I'm assuming you are tracking somewhere at which address the contract was created, and noted that this was not consistent with the expected address?

**Comment by haltman-at** [comment]
Sure, I'll explain.  I'm the maintainer of the Truffle Debugger.  It needs to keep track of what address each call in the callstack is executing at.  Obviously for a `CALL` (or similar) this can be determined from the arguments to it; for a `CREATE` or `CREATE2`, we instead look ahead on the stack to when it returns.  Of course, this doesn't work if the creation fails!  For a `CREATE` there's not really anything we can do about this (we simply don't have the nonces) so we give up and pretend it's 0, which isn't right but is the best we can do; but for a `CREATE2` I was like, hey, why not make it so that we compute the address manually if the creation fails?  Because in this case we do have the information.

Naturally, I wanted to make sure I'd done this right, so I wrote a test.  The test runs a transaction which includes a `CREATE2` that fails.  Specifically, it runs it on a private Ganache network, and Ganache uses ethereumjs-vm.  Strictly speaking the error could be somewhere in Ganache rather than in ethereumjs-vm, but I'm told that Ganache should just pass this sort of thing through without alteration, so I figured I'd just skip ahead and submit the issue here; hope that's OK.

Anyway, during that `CREATE2`, the test uses Solidity's `this`, i.e. the `ADDRESS` opcode, to get the current address and put it on the stack.  We then compare the address on the stack obtained this way to the address we computed.  If we're computing `CREATE2` addresses correctly, they should match.  And ordinarily, they do.

Except, on rare occasion, they don't, and the test fails.  On looking at these cases, I found that in each case, the error was not in the "actual" address (that we computed), but rather in the "expected" address (that we pulled off the stack)!  The test was supposed to check that we were computing the address right, but in each case it failed, it wasn't that we were computing the address wrong, but rather that the wrong address was being pulled off the stack.  Moreover, in each case of failure, the address pulled off the stack was almost correct, but its high byte had been zeroed.  Thus, this issue.

Now strictly speaking, the error could be in `ADDRESS`, rather than in `CREATE2`.  Or in something else in our test.  But it's only the `CREATE2` tests that ever fail like this.  We have a number of these tests, and this is the only one that ever fails.  If the problem were in `ADDRESS`, you'd expect that, say, our tests of addresses in ordinary calls would occasionally fail with this problem, but they don't.  So I'm assuming that `ADDRESS` is working correctly, and is correctly reporting that `CREATE2` has messed up.

If you like, [here's](https://github.com/trufflesuite/truffle/blob/develop/packages/debugger/test/data/global.js#L334) the actual test.  Sorry, I know it's a bit hard to read, and it won't work by itself.  It would probably be easier to write your own rather than try to use this.  And you could presumably also test `CREATE2` directly, rather than by means of `ADDRESS`.  But for reference, there's the sporadically-failing test.

Hope that's helpful!

**Comment by jochem-brouwer** [comment]
@haltman-at Thank you, I'm looking into this and will let you know if I have some new information! =)

**Comment by jochem-brouwer** [comment]
@haltman-at I cannot seem to reproduce this. Could you check the linked truffle test? I am starting to get the idea the problem is in that test, not in the VM.

It would be very helpful if you can look up and post the following contextual variables in case the expected CREATE2 address does not match the actual CREATE2 address:

```
Address of the contract invoking CREATE2
The salt
The code you are deploying (not the hash of this code)
```

**Comment by haltman-at** [comment]
So, this is embarrassing.  Somehow I had been reading actual/expected backwards this whole time.  The error is indeed on our end.  I'll have to figure out what I'm doing wrong.  Sorry to bother you, closing this!

**Comment by haltman-at** [comment]
...and, just as final confirmation, I figured out where the error was coming from and have now fixed it.  So, yup, that definitely confirms it!
