### ISSUE TITLE
runTx: tx.gasLimit is not honoured?

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#79]
Instead of stopping execution, it just returns a `gasUsed > gasLimit`.

I see this in browser-solidity, which calls `runTx`.

@kumavis did you had such an issue?

**Comment by axic** [comment]
Perhaps this is the reason https://github.com/ethereum/solidity/issues/590 and https://github.com/chriseth/browser-solidity/issues/107 can hang the browser (on top of the buggy compiled code which creates an infinite loop)

**Comment by kumavis** [comment]
interesting - I haven't experienced this

**Comment by wanderer** [comment]
not sure I understand the problem. We check the gas [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCode.js#L162) And the gas values should get passed on down from runTx

**Comment by axic** [comment]
I'm not entirely sure why and how it happens, but you can try it out on https://ethereum.github.io/browser-solidity/#version=soljson-latest.js.

Just enter gas limit = 0 on the second tab of configuration and you'll get resulting gas counts as:
```
Transaction cost: 48 gas. 
Execution cost: -187260 gas.
```

**Comment by axic** [comment]
@
![screen shot 2016-07-14 at 17 44 55](https://cloud.githubusercontent.com/assets/20340/16847807/b7c99dd8-49ea-11e6-92d0-1f7dbb9a3107.png)

**Comment by axic** [comment]
@wanderer somehow it manages to set the value wrongly in the tx (I guess BN is at fault?).

`3000000` ends up being `runCode with gasLimit 14408207336905284` and `0` being `runCode with gasLimit -366012`

So the only problem left is that a negative gasLimit shouldn't start execution at all.

**Comment by kumavis** [comment]
maybe parsing as unicode instead of hex string?
try hex prefixing the gas value

**Comment by axic** [comment]
@kumavis moved on to `new BN(<val>, 10)` because internally -tx will use `ethereumjs-util.toBuffer` -- ahh, the mess -- at that supposed to work.

Still seeing an issue with the code letting it run with negative gas after the base fee is subtracted.

**Comment by kumavis** [comment]
maybe BN vs BigNumber confusion ?

**Comment by axic** [comment]
Added debugging to the code @wanderer pointed to:

![screen shot 2016-07-14 at 19 04 15](https://cloud.githubusercontent.com/assets/20340/16850165/c8826096-49f5-11e6-96da-af41c74a8793.png)

Seems like the OOM clause doesn't actually stop the execution.

**Comment by axic** [comment]
The real culprit was browser-solidity's assumption that `result.vm.exception !== 0` means an exception, while the opposite is true.

Fixed: https://github.com/ethereum/browser-solidity/pull/130/commits/71ea03c5efc1c3e6fb363c0e92d5ed67403131b6
