### ISSUE TITLE
Incorrect chainId for goerli

### ISSUE THREAD

**Issue by chaitanyapotti** [ethereumjs/ethereumjs-vm#790]
According to official [github repo]((https://github.com/goerli/testnet)) for goerli, their chain id is 5 and not 6284 anymore.

But, [this file](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/common/src/chains/index.ts) mentions it as 6284. Please update it.

**Comment by evertonfraga** [comment]
Thanks @chaitanyapotti. I'm on it.

**Comment by chaitanyapotti** [comment]
Hey @evertonfraga Any timeline for the release?

**Comment by evertonfraga** [comment]
@chaitanyapotti I will prepare a backported version of Common library, can release later today.

**Comment by chaitanyapotti** [comment]
Hey @evertonfraga , we're still waiting on the release. Can we expect it soon?

**Comment by VoroshilovMax** [comment]
Very interesting!!!

**Comment by evertonfraga** [comment]
The patch is available now via npm. Thanks for your patience, @chaitanyapotti.
