### ISSUE TITLE
ActivatePrecompiles does not what it is expected to do

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-vm#796]
Assumption: if I create a VM with `activatePrecompiles` set to `true`, I expect that precompiles are "activated", which I expect to mean that the accounts are set to non-empty (if we call them from a contract, we expect that `callNewAccount` gas is **not** deducted). 

When we `activatePrecompiles`, every precompile address is filled with a `new Account()`. However:

```
let address = ("a").repeat(40)
vm.stateManager.putAccount(address, new Account())
vm.stateManager.accountIsEmpty(address).then(console.log)
```

=> `true`.

Hence the account is still empty.

Ganache fixes this by instantiating each account with a balance of nonzero. In that case the account is nonempty (we can also set the nonce of the account to 1, or set the codehash to something which is not `KECCAK256_NULL_S`, but these seem a bit weird). So I propose we instead put a balance of 1 wei in those accounts to properly activate them.

**Comment by alcuadrado** [comment]
Nice catch, @jochem-brouwer !

`activatePrecompiles` is indeed intended to do what you described. I think adding 1 wei to the precompiles is the best solution, as it's the less disruptive one.

I just checked, and all the precompiles have non-zero balance on mainnet, including the BLS ones.
