### ISSUE TITLE
Zeros(32) seems to be a default account if none exists

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-vm#800]
If `to: null` is used (or anything that's falsy) then `zeros(32)` seems to be the default setting. However, I find this rather dangerous.

There often is confusing about what one should use when creating a contract. You are actually calling `null`, you are **not** calling the zero address (i.e. 0x00000..0000). For instance, check some mainnet transactions which go to the zero address. If those would actually create a contract, then these transactions which have value would thus create (if calldata is empty) an empty contract at another contract of the zero address. This is also reflected in the Yellow Paper: to create a contract, call B_0 (bytes with length 0, i.e. the null byte), while if you call something in B_20 (bytes with length 20) then call to this address as a normal message call.

I think we should review this code as in some cases the `zeros(32)` is used as account if none is provided (why is this not `zeros(20)`?) and the environment is then instantiated by loading this account. This might lead to some very obscure bugs. This is mainly a call to review this code. I am not really sure what to do with this, I tend to lean to actually using null or `zeros(0)` if a falsy value is provided, as this corresponds to the Yellow Paper.

**Comment by holgerd77** [comment]
Can you give some first code references here and also some external reference to the Yellow Paper or similar? This would be helpful, thanks! 😄

**Comment by jochem-brouwer** [comment]
Of course! [Yellow paper, page 4](https://ethereum.github.io/yellowpaper/paper.pdf), section 4.2, "The Transaction". 

![image](https://user-images.githubusercontent.com/29359032/86128224-64d04480-bae1-11ea-9094-2906e1c3cebc.png)

[runCode.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/0b11b9acecfebb3cc72e807e6f9b38d4c08b28fc/packages/vm/lib/runCode.ts#L90)
[evm.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/fb82f4099e24705c05c0222f97c2f16e2ef841bf/packages/vm/lib/evm/evm.ts#L287)

A follow-up question would be: why is `zeros(32)` used? Why not `zeros(20)`? (Addresses are 20 bytes). Maybe this is to not get any collisions with "real" addresses? I find it weird nevertheless.

**Comment by ryanio** [comment]
this might be able to improved with the new `Address` type in ethereumjs-util [v7.0.5](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.5), where null !== [`Address.zero()`](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/classes/_address_.address.md#static-zero)

**Comment by holgerd77** [comment]
I am actually always too confused by these discussions - so on the questions in what kind of occasion an empty Buffer, a zero Buffer, a padded 0 Buffer,... should be used, that's why I am so unresponsive on these issues.

Some more commenting on this in the respective code parts would likely be helpful (for me as well as for others).

**Comment by jochem-brouwer** [comment]
Closed, #919
