### ISSUE TITLE
Cache.flush: Cannot read property 'modified' of undefined

### ISSUE THREAD

**Issue by jesusdiazvico** [ethereumjs/ethereumjs-vm#81]
Cache.flush (invoked by runCode) throws:

```
/home/test/evm/node_modules/ethereumjs-vm/lib/cache.js:89
    if (it.value.modified) {
          ^

TypeError: Cannot read property 'modified' of undefined
    at /home/test/evm/node_modules/ethereumjs-vm/lib/cache.js:89:33
    at Object.async.whilst (/home/test/evm/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:792:13)
    at Cache.flush (/home/test/evm/node_modules/ethereumjs-vm/lib/cache.js:86:9)
    at parseVmResults (/home/test/evm/node_modules/ethereumjs-vm/lib/runCode.js:234:31)
    at /home/test/evm/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:789:30
    at /home/test/evm/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:167:37
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Of course, just adding "it.value &&"  as precondition in the if prevents the error, but I'm not sure if it breaks something else...

**Comment by holgerd77** [comment]
Experimented a bit with this, not really sure what to do with it. What is the functionality of the ``populateCache`` option and in what context would this be used? Am I correct that this is deactivated atm? Would be nice if anyone can drop a note.

**Comment by andrevmatos** [comment]
Getting it with ganache-cli, trying to mine 500 blocks in a loop. Adding the validation above makes it run without error, but  it's annoying anyway.
