### ISSUE TITLE
JSON serialization of a Transaction is not compatible with go-ethereum?

### ISSUE THREAD

**Issue by cgrigis** [ethereumjs/ethereumjs-vm#816]
Serializing a `Transaction` with `.toJSON()` produces JSON (through the implementation in [`defineProperties()`](https://github.com/ethereumjs/ethereumjs-util/blob/master/src/object.ts#L17)) which is not compatible with the `go-ethereum` [unmarshaller](https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L151]). For example, with 0 numbers, it produces `"0x"`.

I went around this by using the RLP serialization instead, but is the JSON serialization meant to be compatible with the Go version?
If not, feel free to ignore this. :)

**Comment by ryanio** [comment]
thanks @cgrigis for reporting, I am actually working on the tx package now in #812 so it would be a good time to address this if needed.

does `0x` not convert to zero? what happens with that value in the unmarshaller?

**Comment by cgrigis** [comment]
Hi @ryanio, thank you for looking into this!

Here are a few more details:

First of all, it seems `toJSON()` has to be called explicitely with `true` to get an object representation, otherwise an array is returned, which fails in Go with
```
json: cannot unmarshal array into Go value of type types.txdata
```
This is surprising to me according to [this description of `toJSON`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior).

Now an example of the JSON representation of a transaction I get with `JSON.stringify(tx.toJSON(true))`:
```json
{
  "nonce": "0x",
  "gasPrice": "0x01",
  "gasLimit": "0x989680",
  "to": "0x",
  "value": "0x",
  "data": "0x608060405234801561001057600080fd5b506040516020806101cb833981018060405281019080805190602001909291905050508060008190555080600181905550600060028190555050610172806100596000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063a1ff2f5214610051578063ea319f281461007e575b600080fd5b34801561005d57600080fd5b5061007c600480360381019080803590602001909291905050506100a9565b005b34801561008a57600080fd5b5061009361013c565b6040518082815260200191505060405180910390f35b6001548111151515610123576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260058152602001807f6572726f7200000000000000000000000000000000000000000000000000000081525060200191505060405180910390fd5b8060015403600181905550806002540160028190555050565b60006001549050905600a165627a7a723058207721a45f17c0e0f57e255f33575281d17f1a90d3d58b51688230d93c460a19aa00290000000000000000000000000000000000000000000000000000000000000064",
  "v": "0x25",
  "r": "0x5e86d4a36955b93c639479587bc68f20c464893b704beb56fd95e68ca79f6a07",
  "s": "0x3914609b89845d488d37b4e9d1ff5b966b13fb7e841f1ff60ccd7b016be7dc22"
}
```

Trying to unmarshal this in Go I get:
```
json: cannot unmarshal hex string "0x" into Go struct field txdata.nonce of type hexutil.Uint64
```

**Comment by alcuadrado** [comment]
I think the problem is that the intention of that method is not clear. It has a very unique way of encoding things, that partially resembles the ethereum json rpc format, but treats everything as buffers.

How are you using these json? Via the rpc?

**Comment by cgrigis** [comment]
> I think the problem is that the intention of that method is not clear. It has a very unique way of encoding things, that partially resembles the ethereum json rpc format, but treats everything as buffers.

Agreed, which is why I was asking at the beginning whether it was meant to be compatible with the Go version :)

> How are you using these jsons? Via the rpc?

I am sending the transactions to a backend that will use the go-ethereum code to [execute](https://github.com/dedis/cothority/blob/master/bevm/contract.go#L279-L344) them. It is part of the [Ethereum compatibility-layer for the ByzCoin project](https://github.com/dedis/cothority/tree/master/bevm).

Like I mentioned, I went around this by using the RLP encoding. I just thought I'd open an issue in case this was an oversight.

**Comment by alcuadrado** [comment]
I've been thinking about this, and I don't think it'd be reasonable to make this library's API dependant on a geth API. That would mean that any change in geth can force us to release a new major.

I would be a different story if we want it to match the ethereum json rpc format, as that's a standard that shouldn't change.

**Comment by cgrigis** [comment]
Good point, the go-ethereum format does not seem to match the json-rpc either; it is close though, AFAICT the difference is in "input" instead of "data".
In particular, checking the points in the above discussion:

* `"0x"` values [are not legal](https://eth.wiki/json-rpc/API#hex-value-encoding) in the json-rpc format
* json-rpc [uses "gas" instead of "gasLimit"](https://eth.wiki/json-rpc/API#parameters-23)

In any event, from your answers, I understand that the format had no intention to match the Go structure, so you can safely close this issue. Thanks for looking into it! :)

**Comment by holgerd77** [comment]
Close suggested in the preceding comment, will do.
