### ISSUE TITLE
[bug] ethereumjs-tx, Transaction class's `sign` function causes segmentation fault (core dump) on alipine linux

### ISSUE THREAD

**Issue by wanseob** [ethereumjs/ethereumjs-vm#817]
The tutorial works very well on Ubuntu but on Alpine it causes segmentation fault when I try to call `sign()` method.
Found this bug using the docker image `node-12:alpine`.

**Comment by wanseob** [comment]
Related issues

https://github.com/ethereum/js-ethereum-cryptography/issues/3
https://github.com/cryptocoinjs/keccak/issues/15
https://github.com/ethereumjs/ethereumjs-util/issues/266

**Comment by alcuadrado** [comment]
Closing this issue as it was followed and fixed in https://github.com/cryptocoinjs/keccak/issues/15
