### ISSUE TITLE
runCall invoked twice for DELEGATECALL

### ISSUE THREAD

**Issue by raineorshine** [ethereumjs/ethereumjs-vm#82]
"When calling a contract function that calls into a library, the Ether sent in the transaction is spent multiple times."

This issue was originally started on testrpc: https://github.com/ethereumjs/testrpc/issues/122 as reported by @graup.

I have narrowed down the issue to `runCall` being invoked twice. It runs once as part of [`runBlock > runTx > runCall`](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runTx.js#L47) and once as part of [`DELEGATECALL > makeCall > runCall`](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L658). 

I assume that the problem is in `DELEGATECALL` since that is doing the library function invocation (the reproducible element). Not knowing more about ethereumjs-vm internals, I am unsure whether `DELEGATECALL` needs to simply remove the `makeCall` invocation or if a subset of makeCall/runCall functionality must be removed. Would like to get input from @tcoulter or someone with more understanding of the codebase before proceeding. Cheers!

**Comment by raineorshine** [comment]
@tcoulter I'm wondering if you have any hints about moving forward. I'm happy to put some work into this issue. I just know that 5 min of your guidance might save me a couple hours of searching since I am unfamiliar with the codebase.

**Comment by tcoulter** [comment]
Looks like we need to add an option to only do this conditionally: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCall.js#L52

Then have `DELEGATECALL` pass that option to `makeCall`, and have `makeCall` pass it to `runCall`. That'd at least be the quick and dirty option.

**Comment by kumavis** [comment]
without looking at the code, my guess is that we are removing the balance from the apparent sender (the sender DELEGATECALL is impersonating) rather than the actual emitter of the message.

**Comment by kumavis** [comment]
@wanderer did we not get new tests after the last feature fork?

**Comment by wanderer** [comment]
@kumavis they may be in ethereum/tests but I didn't explicitly add them.

@raineorshine @tcoulter so what would help here the most is if you could give me the minimal amount of EVM byte code that doesn't perform as expected.  DELEGATECALL does indeed make a call and that is why it is calling makeCall then runCall

**Comment by tcoulter** [comment]
@wanderer I can give you bytecode. The issue is that the transaction value is getting subtracted twice, which isn't necessarily related to bytecode, however.

**Comment by kumavis** [comment]
@tcoulter @wanderer just wants a minimum failing test that he can fix

**Comment by raineorshine** [comment]
There is a failing test case provided in this testrpc PR. Would this be
sufficient?

https://github.com/ethereumjs/testrpc/pull/123

**Comment by kumavis** [comment]
we need to add a test to the `ethereumjs-vm` repo that doesn't add additional dependencies (especially circular deps like `testrpc->ethereumjs-vm->testrpc` )

**Comment by raineorshine** [comment]
Here is the minimal Solidity code needed to reproduce the bug:

```
library MyLib {
  function doNothing() {
  }
}

contract Contract {
  function() {
    MyLib.doNothing();
  }
}
```

I looked at the tests in ethereumjs-vm and it wasn't obvious where I would set up a test case. Or does a test need to be added to the official ethereum tests? Any tip to point me in the right direction would be helpful. Thanks!

**Comment by wanderer** [comment]
@raineorshine @tcoulter can you try this change?
https://github.com/ethereumjs/ethereumjs-vm/pull/84/files
Let me know if that fixes your problem and then we will merge

**Comment by raineorshine** [comment]
@wanderer Unfortunately, no. The sending account is still reduced by twice as much as it should.

**Comment by mrbodoia** [comment]
Any updates on this issue? I use TestRPC for all of my contract prototyping and testing and find it extremely useful, but the fact that it can't process library calls correctly is becoming more and more difficult to work around.

I'd be happy to lend a hand in fixing this, but I'm not sure how much help I'll be given the complexity of the VM codebase.

**Comment by axic** [comment]
The reason this wasn't caught by the tests is they were from January and Homestead (delegatecall) came out after that time :wink:
