### ISSUE TITLE
Make `memory.ts` use Buffers instead of Arrays

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-vm#827]
[Memory.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/evm/memory.ts) is currently implemented using Arrays. While this is a bit simpler than using Buffers, this does lead in non-optimal memory management especially when we copy things around. If we implement memory using Buffers I think that this could lead to some speed-up of the VM. Most contracts compiled by solidity don't re-use memory but instead keep writing to new free space every time, so it is likely that this will lead to noticeable speed-ups if we compare mainnet blocks either using the Array implementation or the Buffer implementation.

**Comment by alcuadrado** [comment]
Yes! I have the same impression. I just don't have any kind of intuition on how much faster the VM would run after this.

**Comment by holgerd77** [comment]
Should likely be worth a try given the low complexity of the `memory.ts` class?

**Comment by alcuadrado** [comment]
Yes, sure. It should be pretty straightforward

**Comment by holgerd77** [comment]
Likely worth to wait for the benchmark work from @s1na to be merged https://github.com/ethereumjs/ethereumjs-vm/pull/794
