### ISSUE TITLE
Implement EIP-2876

### ISSUE THREAD

**Issue by junderw** [ethereumjs/ethereumjs-vm#834]
Related issue: https://github.com/ethereum/web3.js/issues/3688

I will handle the implementation.

I am making this issue to discuss / ask about the methodology / get a loose green-light on the EIP before diving in on implementation.

## The EIP

https://eips.ethereum.org/EIPS/eip-2876

## My Plan

1. Allow accepting a deposit address in the `to` field, but it will throw if the data field is not blank, and if blank it will properly insert the necessary data and replace the to field with the proper 20 byte address internally.

Any thoughts about my plan for implementation here should go in this thread.

Any thoughts about the EIP itself should go to the Discussions-To thread on the EIP.

Thanks for your time and I look forward to making things easier for exchanges and merchants (and lowering overall gas usage from value transaction based systems with naive forwarding)

**Comment by jochem-brouwer** [comment]
I am not sure if this is the right repository for this issue. It seems that this EIP can be directly implemented (it is an ERC-20 like EIP) without any necessary changes to this monorepo (or consensus issues in general). Correct me if I'm wrong.

If this is purely to discuss the EIP you might consider opening a thread [Ethereum Magicians?](https://ethereum-magicians.org/)

**Comment by junderw** [comment]
Yes. The ERC can be directly implemented using the existing version.

However, if the `to` field accepted deposit addresses directly (and automatically, in the background, set the `data` field) then "support" of the ERC will just be "upgrade to latest version of ethereumjs-tx."

One of the main goals of creating the EIP was to make an easy-to-implement single-purpose address format (and corresponding contract interface).

Think of it like implementing EIP-55 address-with-checksum support, but it requires data to be empty and sets the data according to the EIP.

By adding this new address support, any exchange that is sending value-tx withdrawals etc. only needs to update and suddenly they can send to these addresses properly.

**Comment by junderw** [comment]
Looking into the implementation of this library, I notice even EIP-55 address checksums are not checked...

In that case it does seem that this library in particular should not implement such a convenience thing (seeing as it is a very thin wrapper over an ethereum tx.)...

I will try to cover by adding examples.

Thanks.
