### ISSUE TITLE
Release a "develop" tagged package on npm mirroring the current master branch

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-vm#841]
Currently, we are almost at the point where we want to release V5 of this monorepo. This of course brings some breaking changes. For instance, on ethereumjs-client we now need to change blockchain/ethash from their callback version to the native promise version. To smoothen this develop experience without having to create local npm packages I think it is a good idea in general to release a develop version of this package on npm, so we can start integrating these changes in other repositories. Of course this version is not a stable version, but I think it is handy in general since people might want to checkout the latest VM version without too much hassle.

**Comment by jochem-brouwer** [comment]
It looks like we had `beta` tagged npm releases in the past? (`4.0.0-beta.1` on [npm](https://www.npmjs.com/package/ethereumjs-vm)). We might want to start re-using this in the future? (Currently we'd then have a `5.0.0-beta` which would also give us a bit more incentive to keepcChangelog/docs updated).

**Comment by holgerd77** [comment]
I would regard this as "sufficiently solved" for now. We have released the big v5 versions - so no more backlog from that side any more, went through the process of doing `beta` releases (and could do again in between normal releases if there is a demand) and have more packages integrated in the monorepo now. We will likely also switch to a regular release cycle now with releases every 2-4 weeks. All this should leverage weight from the issue. Feel free to reopen though if needed, will close for now.
