### ISSUE TITLE
"Error: Transaction has been reverted by the EVM" while sending transaction via ropsten infura testnet

### ISSUE THREAD

**Issue by emrem6** [ethereumjs/ethereumjs-vm#848]
I want to call the following function in the smart contract and do a transaction on the ropsten testnet:

`
function setOffer(uint256 _offerPrice, string memory _fileHash, address payable _client, address payable _provider) public {
        offerCount++;
        offers[offerCount] = Offer(
            offerCount,
            _offerPrice,
            _fileHash,
            _client,
            _provider,
            false
        );
    }
`

The contract is deployed via remix IDE on Ropsten Testnet. I am using infura as a provider. I am not sure but I think this function requires a transaction because it is state-changing. 

So I wrote the following code:
`var Tx = require('ethereumjs-tx').Transaction;
var privateKey = Buffer.from('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'hex');

async function writeOfferToContract(_offerprice, _fileHash, _contract, _client, _account) {
    var data = await _contract.methods.setOffer(_offerprice, _fileHash, _client, _account).encodeABI();
    var nonce = await web3.eth.getTransactionCount(_account);
    nonce = '0x' + nonce.toString(16);

    var rawTx = {
        nonce: nonce,
        gasPrice: web3.utils.toHex('1000000000'),
        gasLimit: web3.utils.toHex('210000'),
        to: '0x8285ed4dbfba6faa5bd9da628579239168dd2e06',
        value: web3.utils.toHex(_offerprice),
       data: data,
        chainId: 3 //ropsten = 3
    }

    var tx = new Tx(rawTx, { 'chain': 'ropsten' });
    tx.sign(privateKey);

    var serializedTx = tx.serialize();

    if (_offerprice != 'undefined' && _contract != 'undefined') {
        try {
            console.log(_contract.methods)

            const receipt = await web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'), function (err, hash) {
                if (!err)
                    console.log('ERROR:', hash); // "0x7f9fade1c0d57a7af66ab4ead79fade1c0d57a7af66ab4ead7c2c2eb7b11a91385"
            });
            console.log(receipt)
            console.log('OFFER SUCCESSFULLY WRITTEN IN CONTRACT')
        } catch (error) {
            console.log('Error in setOffer: ', error)
        }
    }
}
module.exports = {
    writeOfferToContract
};`

 

The Transaction is running through but I get the Error: 
`{ Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x168f3ab8b55faf29f72709f00c7a1c974bc0ea46837d25e00900556dd9386fa2",
  "blockNumber": 8568360,
  "contractAddress": null,
  "cumulativeGasUsed": 6274024,
  "from": "0x2692dea243c0341a48ba9017e84d5bc4ab1d2e0d",
  "gasUsed": 21046,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x8285ed4dbfba6faa5bd9da628579239168dd2e06",
  "transactionHash": "0x1575f945cfadbaed1c235dabeab91b7cf30c4c8581d250565ed7a6d70e9b0da4",
  "transactionIndex": 35
}
    at Object.TransactionError (/home/emre/CARDAMOM/PrinterApp/node_modules/web3-core-helpers/src/errors.js:93:21)
    at Object.TransactionRevertedWithoutReasonError (/home/emre/CARDAMOM/PrinterApp/node_modules/web3-core-helpers/src/errors.js:105:21)
    at /home/emre/CARDAMOM/PrinterApp/node_modules/web3-core-method/src/index.js:474:48
    at process._tickCallback (internal/process/next_tick.js:68:7)
  receipt:
   { blockHash:
      '0x168f3ab8b55faf29f72709f00c7a1c974bc0ea46837d25e00900556dd9386fa2',
     blockNumber: 8568360,
     contractAddress: null,
     cumulativeGasUsed: 6274024,
     from: '0x2692dea243c0341a48ba9017e84d5bc4ab1d2e0d',
     gasUsed: 21046,
     logs: [],
     logsBloom:
      '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     status: false,
     to: '0x8285ed4dbfba6faa5bd9da628579239168dd2e06',
     transactionHash:
      '0x1575f945cfadbaed1c235dabeab91b7cf30c4c8581d250565ed7a6d70e9b0da4',
     transactionIndex: 35 } }`

I am trying to find the problem since days but I dont know what causes the Error. On etherscan I can see the transaction but it is marked with Fail. 
Maybe someone can help me..

**Comment by jochem-brouwer** [comment]
Hey there, this is not really in the scope of the `tx` package as this has to do with your interaction with the blockchain and not really about internal functionality of this tx.

I checked your transaction and the `data` field of the transaction is actually empty. This might be part of the problem you are facing.

**Comment by holgerd77** [comment]
Will close here for now. @emrem6 feel free to reopen if you still think this is an issue.
