### ISSUE TITLE
Publish npm packages for each PR

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#890]
The chosen tool is PikaCI.

Resources:
- [Website](https://www.pika.dev/)
- [Marketplace](https://github.com/marketplace/pika-ci-cd)
- [App](https://github.com/apps/pika-ci)

**Comment by ryanio** [comment]
https://github.com/pikapkg/pack#lerna-support

**Comment by evertonfraga** [comment]
This experiment didn't fly. Maybe this can be tackled at some point in the future.
