### ISSUE TITLE
Prepare to welcome ethereumjs-devp2p and ethereumjs-client packages

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#892]
## devp2p

[Preparatory issue tracking](https://github.com/ethereumjs/ethereumjs-devp2p/issues/86)

- [x] Migrate code, tags, documentation links and etc, using [Monorepify](https://github.com/evertonfraga/monorepify-ethereumjs)
- [ ] Add info and badges to the root readme
- [ ] Create new issue template
- [ ] Create dedicated label for the project
- [ ] Configure codecov

## client

[Preparatory issue tracking](https://github.com/ethereumjs/ethereumjs-client/issues/142)

- [x] Migrate code, tags, documentation links and etc, using [Monorepify](https://github.com/evertonfraga/monorepify-ethereumjs)
- [x] Add info and badges to the root readme
- [ ] Create new issue template
- [ ] Create dedicated label for the project
- [ ] Configure codecov

**Comment by jochem-brouwer** [comment]
I don't think we should close this; we don't have issue templates for devp2p/client for instance.

**Comment by holgerd77** [comment]
Will do a housekeeping-PR today fixing some remaining stuff.

**Comment by ryanio** [comment]
This has been completed 👍
