### ISSUE TITLE
Restrict Benchmark workflow for contributors only

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#904]
It seems the benchmark workflow fails under external fork setups.

We should restrict it, or avoid running their commands in such cases. 
https://github.com/ethereumjs/ethereumjs-vm/pull/903/checks?check_run_id=1215401445

**Comment by holgerd77** [comment]
Seems to be working now (not sure when this was fixed and in what context) - see e.g. https://github.com/ethereumjs/ethereumjs-vm/pull/974 - will close for now, feel free to reopen if necessary.
