### ISSUE TITLE
Deprecate last ethereumjs-account Release

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#912]
The latest `ethereumjs-account` `v3.0.0` release on [npm](https://www.npmjs.com/package/ethereumjs-account) should be marked as `DEPRECATED` with the removal of the package along #911 mentioning the now to be used `Util.Account` class introduced along https://github.com/ethereumjs/ethereumjs-util/pull/275 to make people aware that they should update.

**Comment by evertonfraga** [comment]
Done.

NPM package page:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/47108/98141944-34385700-1e95-11eb-8272-5689d5112922.png">

https://www.npmjs.com/package/ethereumjs-account

Installing with Yarn:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/47108/98141640-d7d53780-1e94-11eb-9f4a-d1e97b6e4940.png">

Installing with NPM:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/47108/98141828-13700180-1e95-11eb-8153-b4791eeb2c8c.png">

Adding the same deprecation notice on the once archived repo:
https://github.com/ethereumjs/ethereumjs-account/pull/65

**Comment by holgerd77** [comment]
👍  Thanks, nice deprecation message! 😄
