### ISSUE TITLE
Implement EIP150

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#92]
See https://github.com/ethereum/EIPs/issues/150.

**Comment by mhhf** [comment]
When can we expect this to be implemented?

**Comment by PeterBorah** [comment]
Is this still in progress? This has been live on mainnet for a couple months, afaik.

**Comment by sdtsui** [comment]
Will review over the weekend.  @axic - is this something I can claim/help with? Shoot me a DM on Gitter, we could arrange a time to jump on a call after my dev env is set up to familiarize myself with `ethereumjs-vm` and (as @wanderer indicated) parts of the python codebase we're working off of..

Thanks!

**Comment by ercpereda** [comment]
Hi, @sdtsui I saw you have PR, is there anything I can do to help close the issue?

**Comment by cdetrio** [comment]
Closed by https://github.com/ethereumjs/ethereumjs-vm/pull/143
