### ISSUE TITLE
VM exposes too much stuff

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#924]
If one is doing an autocomplete on the `node` console there are just far too many instance members and functions being visible, and all in a very much inconsistent state regarding the naming of somewhat private methods with `_` or not. Here is an example screenshot on this:

![Bildschirmfoto 2020-10-22 um 12 49 48](https://user-images.githubusercontent.com/931137/96862640-0a7b3b00-1466-11eb-9e3f-3dd652675244.png)

This is not very user friendly for people playing around with the VM and should be urgently cleaned up, optimally in a way that non-public members are not visible at all, minimally by adding underscores to give some orientation.

This should be done along the pre-release period since changes are pretty small with a significant effect, changes are also very much on the clean-up / consolidation side.

(also from a breaking/non-breaking aspect this is advisable to do now since people might use this exposed stuff unintentionally and will stumble if this is cleaned up along minor releases. If someone is missing something afterwards we can have an official discussion if something is worth to be re-exposed)

**Comment by jochem-brouwer** [comment]
How exactly can we hide these properties, so they do not show up in node? I'd think something like `Object.defineProperty`?
