### ISSUE TITLE
Failing nightly build

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#928]
The nightly build failures are due to massive Constantinople test failures for both State and Blockchain.

The current CI structure does not make easy to inspect specific errors, as they are under a single command (`npm run test:state:allForks`), so I had to run each test suite to investigate it:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/47108/97483958-7fe77f80-192e-11eb-869a-fcae7f403d09.png">

**Comment by jochem-brouwer** [comment]
This is very suspicious, especially because it is one HF! Why does Constantinople throw?

**Comment by evertonfraga** [comment]
I'll dive into root causes after running the blockchain tests, which can't be run in parallel, because of db resource allocation (the path is fixed).

**Comment by evertonfraga** [comment]
After a `git bisect` session, I found the offending PR: https://github.com/ethereumjs/ethereumjs-vm/pull/889/, which has some Constantinople-specific code changes. 

@cgewecke can you quickly spot the error here? Otherwise I can debug with more depth. Thanks!
