### ISSUE TITLE
Node Version tests failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#963]
Currently these new Node version tests from #939 introduced by @evertonfraga are [failing](https://github.com/ethereumjs/ethereumjs-vm/runs/1445212877?check_suite_focus=true).

We might want to have a look into this before we do the releases on Thursday.

**Comment by evertonfraga** [comment]
The test code can't reach the ethereum/tests submodule. It tries to fetch data from ./packages/ethereum-tests

Please check if the node tests yml config contain the `submodules: recursive` directive. 

Thanks!
