### ISSUE TITLE
Misleading description in runCode

### ISSUE THREAD

**Issue by chiro-hiro** [ethereumjs/ethereumjs-vm#979]
```ts
  /**
   * The address that ran this code. Defaults to the zero address.
   */
  caller?: Address
```
https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runCode.ts#L37-L40
Do you mean the address that trigger this code?. Is that `msg.sender`?

```ts
  /**
   * The address of the account that is executing this code. Defaults to the zero address.
   */
```
https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runCode.ts#L60-L63
This description very confused, I did test and this one is `address(this)`. Could we change this one to address of smart contract?.

**Comment by jochem-brouwer** [comment]
Hey there! `caller` is `msg.sender` and `address` is `address(this)` (the smart contract address, the address containing the code, etc.). Do you think we should add that to the description?

**Comment by chiro-hiro** [comment]
@jochem-brouwer Yes please, It sounds easier to understand.

**Comment by holgerd77** [comment]
Will close here since these small issues tend to bloat the issue list unproportionally, but have added this to our tiny-fixes meta issue linked above, so this will be addressed along a subsequent PR.
