### ISSUE TITLE
Client Node Version tests fail

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#980]
[Client test run](https://github.com/ethereumjs/ethereumjs-vm/runs/1489806215?check_suite_focus=true) - at least on Node 14 - during the nightly Node version test run currently fail with 6 failed tests along the integration test run.

This should be investigated and fixed.

Also: is there a way to set CI up here in a way to not stop early but continue the other Node version tests independently from a failed version test run? Think this would make more sense, on the run above the Node 10 and 12 tests were canceled before execution.

**Comment by jochem-brouwer** [comment]
Related: #996

**Comment by ryanio** [comment]
> Also: is there a way to set CI up here in a way to not stop early but continue the other Node version tests independently from a failed version test run? Think this would make more sense, on the run above the Node 10 and 12 tests were canceled before execution.

yep, can set [`fail-fast`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to `false`

**Comment by jochem-brouwer** [comment]
When I check the changelog I see that Node v13 is marked as End Of Life. Would it make sense to instead start supporting the Long Term Support versions? (And the latest?). This would mean that we would test client on node v10, v12, v14 and v15?

**Comment by jochem-brouwer** [comment]
OK, interesting; v14.0.0 also fails, but it does not fail on the test "should sync with best peer" (`integration/fullsync.spec.ts`), later versions (v14.15.3) also fail on this test.
