### ISSUE TITLE
Client creates `segmentation fault` on alpine linux (docker)

### ISSUE THREAD

**Issue by PhilippLgh** [ethereumjs/ethereumjs-vm#994]
#### Description

When the client is executed inside a docker container with alpine image it crashes with `segmentation fault`

Most likely related to https://github.com/cryptocoinjs/keccak/issues/15.
The alpine image is recommended by `hive`, so it would be great if this could get resolved.

It  is probably a problem with native code and could be caused by a `musl` vs `glibc` conflict.

**Comment by alcuadrado** [comment]
I think this can be closed. We figured out that napi modules had to be shipped with support for two libcs, and that was done.

**Comment by holgerd77** [comment]
@alcuadrado Ok, thanks 👍 , will close.
